### PR TITLE
added storage dir path options

### PR DESCRIPTION
**Pull request by Smug246**
From discussion https://github.com/zauberzeug/nicegui/discussions/1418

### CODE REVIEW

**Comment by rodja** [comment]
I think we should not use the temp directory as default to store persistent data. temp gets potentially cleaned a lot, and would defeat the purpose of the persistence.

**Review by falkoschindler — CHANGES_REQUESTED** [review]
Thanks for the quick PR, @Smug246! Just a few remarks:

- I have to agree with @rodja. At least in 1.3 we don't want to introduce breaking changes. So the default path should be the current working directory.
- And I slightly tend to the parameter name `storage_path` instead of `storage_dir` to avoid an abbreviation and to indicate its path-like nature.
- Last but not least we shouldn't forget to add this parameter to `ui.run_with` for when using NiceGUI with an existing FastAPI app.

**Comment by Smug246** [comment]
np ill make those changes

**Review by falkoschindler — APPROVED** [review]

**Comment by falkoschindler** [comment]
Thanks, @Smug246! I just made a few more changes:
- I removed the special case of "temp". It doesn't make much sense to store data in the temp directory which might not survive a reboot. And it could be confused with a folder named "temp" in the current working directory. Therefore I removed it altogether. This doesn't prevent the user from explicitly setting the temp directory.
- I converted the value to a `Path` object before storing it in `globals`. This way we can use it more easily.
- I set the default value to `Path('.nicegui')` instead of `None`. This communicates the default value more clearly, removes the need for `Optional` and avoids the need for handling `None` later.

A downside of these changes is the duplication of the default value `Path('.nicegui')`. But since the parameter list of `ui.run` and `ui.run_with` is duplicated anyway, I guess this is a reasonable tradeoff.

**Comment by falkoschindler** [comment]
Oh dear, I merged too early. The storage path is already used before `ui.run` is called. Therefore the app can't start.
I'll somehow have to undo this PR on main...

**Comment by falkoschindler** [comment]
This problem seems to be pretty fundamental. Therefore I reverted this PR and re-opened discussion #1418.

**Pull request merged**
