### PR TITLE
File Picker

### PR DESCRIPTION
**Pull request by Diegiwg**
A component which handles the user interaction for picking file

### CODE REVIEW

**Comment by falkoschindler** [comment]
@Diegiwg Thanks for your PR! It's definitely nice to see NiceGUI's collection of UI elements grow.

I just wonder, what is the advantage of `ui.file_picker` over `ui.upload`? Sure, these are different Quasar components, so they might both be useful. But don't they serve the same purpose?

**Comment by Diegiwg** [comment]
As I understand it, File Pick is basically used to 'locally pick up data from a file', that is, it will only be available on the client.

Of course, I believe that if the server requests `file_obj.text()`, as a response from some method, the file content will inevitably be uploaded to the server (hence, I believe it makes more sense to use upload).

Now, if the intention is, for example, to select an image to be shown on the site, or a text file to be read (only on the client, without server interaction with the content), I believe that `ui.file_picker` is the option to be used.

In the Quasar Docs description for each of these elements, we have:

- If you also want a component to handle the upload for you, please consider using QUploader instead.

- If all you want is an input file, you might want to consider using QFile picker component instead.

So, I believe they also 'think' like this: if you want to get the file, use upload, if you just want to load the file locally on the client, use file_picker.

**Comment by falkoschindler** [comment]
Ok, but how to "load the file locally on the client" with NiceGUI? Without upload, NiceGUI can't do anything with the file.

**Comment by Diegiwg** [comment]
Yeah, I tried to use file_pick to create a simple notepad (load and save txt files), but it didn't work, because anyway I need to send nicegui the contents of the file. So apparently this element is not very useful outside the JS world.

**Comment by rodja** [comment]
Should we close this pull request?

**Comment by Diegiwg** [comment]
Probably, I'm  not seeing more use in implementing this element.

**Pull request closed without merging**
