### PR TITLE
Restructure documentation

### PR DESCRIPTION
**Pull request by falkoschindler**
This PR follows up on idea #1807 where @ed2050 proposed a new documentation structure.

I started by refactoring the documentation modules a little bit (https://github.com/zauberzeug/nicegui/commit/1706a111aea7814ee00dacad1141428cdb0b5789)
before moving the actual content into new sections (https://github.com/zauberzeug/nicegui/commit/c262584a11b0cd5b3ab4a4834a9d991ef59d5c16).

Next step will be to split the /documentation page into section pages, so that we never load all demos at once. We'll merge quickly to pave the way for follow-up PRs adding new content and further improving the organization.

### CODE REVIEW

**Comment by falkoschindler** [comment]
I started to implement the new /documentation site which should give an overview of all sections. At the moment it only contains an intro for Text Elements.

I'm not sure if I like it. On one hand I'd like to show some code instead of just text. But on the other hand it somewhat hides the link to the actual element gallery. Should we simply show a grid of cards that link to each section (like the examples on the main page)? Or can we indicate the "intro" character of these demos more clearly?

Screenshot 2023-11-18 at 18 44 05

**Comment by ed2050** [comment]
Nice start.  Here's what I had in mind:
* Intro text paragraph is fine.  I wouldn't put too much text here.
* I picture this index page as primarily a visual gallery.  Can be just static screenshots to reduce server load - no need for live demos of each component.
* I would emphasize the component image and de-emphasize the code.  Full code examples can be found on the relevant component page.  On index page, just show one line of code after the visual example (below or right column).
* Link everything to the component page.  So the heading Label and the label screenshot should be clickable to go to the full page for that component.
* Use a "Quick Links"-type page index to 1) jump to any item on this page and 2) give a quick view of what components are available on this page

This gives you:
1. Quick access to jump to a certain component if you already know what you want
2. A compact list of all components on this page to quickly see what's available.  Even better if the quick links have a mini-screenshot next to them for visual reference.
3. A visual list to scroll through if you don't know what you want or don't remember the name of a component.

It would look something like this (style limited by markdown):

# Text Elements 
Intro para blah blah blah as above

Components on this page:  
* [Label](url)
* [Link](url)
* [Markdown](url)
* [HTML](url)
*  ...  


Click any screenshot or heading below to go to the full reference page for that component.

## Label
Screen Shot 2023-11-19 at 5 29 59 PM

```py
ui.label('some label')
```

## Link
Screen Shot 2023-11-19 at 5 32 49 PM

```py
ui.link('NiceGUI on GitHub', 'https://github.com/zauberzeug/nicegui')
```


## Markdown
Screen Shot 2023-11-19 at 5 34 21 PM

```py
ui.markdown('''This is **Markdown**.''')
```

## HTML
Screen Shot 2023-11-19 at 5 34 53 PM

```py
ui.html('This is <strong>HTML</strong>.')
```

**Comment by falkoschindler** [comment]
Thanks, @ed2050. Right now I'm primarily focussing on splitting the documentation into sections. And my screenshot in https://github.com/zauberzeug/nicegui/pull/2039#issuecomment-1817581630 meant to show the overview page, but I only included the preview for the "Text Elements" section.

Anyway, I agree that it could be more minimal with a larger link area. Therefore I tried using similar tiles like on the front page:

Screenshot 2023-11-20 at 13 32 10

Sure, we could add previews in form of screenshots or live demos, but maybe this would clutter the page again, forcing the user to scroll.

**Comment by ed2050** [comment]
I agree, that looks good if you're showing all elements.  Just a short tile or card.  Screenshot not needed because which element would you show?

I'm confused which page you mean by overview.  I proposed an overview page 1.0 Overview with subpages 1.1 Text Elements, 1.2 Controls, ..., that could also be called overview pages.

Then each section has it own parent page.  2.0 Text Elements is the parent of 2.1 Labels, 2.2 Markdown, etc.  That's the page I thought you were showing above.  And that's the page I was describing.  I call it section page to avoid using overview again.

Your latest reply seems to mean something different.  This would be a new page that lists all components.  Perhaps it's meant as an index to the split pages while the new Overview section is developed?  That makes sense for a quick approach.  The index could be reused later.

Anyway, the screenshot looks good as an overall index.  I agree, images not needed here.  Demos / images belong on the section pages (like 2.0 Text Elements) where you only show one group of components.

**Comment by falkoschindler** [comment]
I think this PR is basically finished. I'm not 100% happy; "back" links from individual "element pages" throw you back to the main documentation page. But I think we should merge and tackle other improvements afterwards.

At the moment I'm re-thinking the whole documentation infrastructure. I'd like to separate content definition and execution, so that we can collect the whole documentation tree as a whole and render the explanations and demos later on demand. This would simplify the code quite a bit, which is starting to get out of control.

**Review by rodja — APPROVED** [review]
Seems to work. Let's merge!

**Pull request merged**
