### PR TITLE
Add support for dependabot

### PR DESCRIPTION
**Pull request by gaby**
- Track the following using dependabot on a daily basis:
  - github-actions
  - python
  - docker
- Bump base image from 3.11.3 to 3.11.9 which is the latest patch release: https://endoflife.date/python 

Related to #3393

### CODE REVIEW

**Review by falkoschindler — COMMENTED** [review]
Thanks for the pull request, @gaby!

Regarding the dockerfiles: I'm not sure why we specify patch versions here. In development.dockerfile we simply use `python:3.8-slim` which should use the latest patch automatically. @rodja Do you remember a reason for using `python:3.11.3-slim` instead of `python:3.11-slim`?

**Comment by rodja** [comment]
I think there was no special reason for fixing on the patch version. We can change it to `3.11-slim`.

**Review by falkoschindler — APPROVED** [review]
Ok, I removed the patch version from the dockerfiles. Let's merge! 👍🏻

**Comment by gaby** [comment]
@falkoschindler Thanks! It already created a few PR's :-)

**Pull request merged**
