### PR TITLE
Improve recovery after reconnecting

### PR DESCRIPTION
**Pull request by rodja**
This pull request tries to implement #1761.

### CODE REVIEW

**Review by falkoschindler — COMMENTED** [review]
@rodja I just tested the implementation with a simple test app:

```py
from nicegui import ui

ui.input('Hello world!')
ui.button('Click me!', on_click=lambda: ui.notify('Button clicked!'))

ui.run(reconnect_timeout=10.0)
```

When I type something into the input field, disconnect the connection via developer tools > network > throttling, wait for the connection popup and reconnect, the input is preserved. But the same happens for `reconnect_timeout = 0`. Shouldn't this trigger a reload?

**Review by falkoschindler — APPROVED** [review]
Sorry, my bad: `reconnect_timeout` has no effect on the auto-index client. 🤦🏻‍♂️

**Comment by falkoschindler** [comment]
@rodja I just got aware of a possibly inconvenient behavior when using `reconnect_timeout = 3` (the new default in version 1.4):

```py
@ui.page('/test')
async def page(client: Client):
    ui.label('Hello, world!')
    await client.disconnected()
    print('disconnected', flush=True)
```

The `client.disconnected` will only return after 3 seconds. Although this is correct and consistent, it might lead to unexpected delays when transitioning to version 1.4.

**Comment by rodja** [comment]
@falkoschindler yes, that's why I chose to use 0 for 1.3. But allowing clients to reconnect without page reload is super important and I would gladly trade the delayed `client.disconnected()` for the benefit of reducing state loss.

**Pull request merged**
