### PR TITLE
ui.splitter element

### PR DESCRIPTION
**Pull request by abulka**
Here is my initial version of a `ui.splitter` element for NiceGUI, incl. test, extra example and documentation.

Happy to iterate and refine this.

### CODE REVIEW

**Review by falkoschindler — APPROVED** [review]
@abulka Thanks for this great pull request! With the new element, demos and tests already in place, we should be able to merge it pretty quickly.

I just looked into the code and tweaked it a little here and there:

- I moved the extra example into the documentation. By shortening the example texts it fits neatly into a little code window. And this way it can be tried out directly on the website.

- On the Quasar website I found the example "Image fun". I just had to translate it to NiceGUI and put it into the documentation. :blush:

- I couldn't reproduce an issue with horizontal splitters. That's why I removed the warning. But let me know if we should to look into it once again.

- I added the three slots "before", "after" and "separator" in the initialzer. This way you can simply use them like `with splitter.before:` and we don't need the warning about them being required.

The only thing left to do seems to be the pytest actually dragging the separator a bit. I couldn't figure out how to do it, yet. An `ActionChains` with `drag_and_drop_by_offset` causes strange error messages. But this missing test shouldn't hold us back to merge and release this new feature.

**Comment by abulka** [comment]
Happy to see those additional changes, and now I see how the pre-defining of slots works - cool.

Re the horizontal splitter - this is what doesn't work for me. The splitter appears, but doesn't move:
```python
from nicegui import ui

with ui.splitter(horizontal=True) as splitter:
    with splitter.before:
        ui.label('This is some content on the TOP side.'*150)
    with splitter.after:
        ui.label('This is some content on the BOTTOM side.'*150)

ui.run()
```

Also, I couldn't get the image splitter example working fullly - the b/w image simply doesn't appear for me. On a Mac using Chrome.
image

**Comment by falkoschindler** [comment]
Very strange... 🤔

The horizontal splitter is working when giving it some fixed height like `.classes('h-96')`. But I'm not completely sure why. Maybe the height computation for the individual slots does not work if the parent container has no fixed size.

And the image example is, indeed, not working in an isolated script. But when starting main.py it looks just fine on the splitter documentation page.

**Comment by falkoschindler** [comment]
I think I fixed the image demo: [556720d](https://github.com/zauberzeug/nicegui/pull/676/commits/556720d043019c4c56089118eb2cfe78549942fe).
As in the original example, both images should be positioned absolutely. But then the splitter needs an explicit height in order not to collapse.

**Review by rodja — APPROVED** [review]
Super cool. Thanks for contributing, @abulka!

**Pull request merged**
