### PR TITLE
Dynamic properties mimetype fix

### PR DESCRIPTION
**Pull request by thetableman**
This PR aims to resolve the `Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". ` error with elements using `dynamic_properties.js`, examples of this error are noted in #1510 and #1579.

Credit to @natankeddem for finding and suggesting the fix in #1579.

### CODE REVIEW

**Comment by thetableman** [comment]
Tested the additional `mimetype` in ~__init__.py` of the main nicegui directory and in `ui.py` however the issue persisted. Applying to `element.py` resolved the issue for me for both `echart` and `aggrid` elements.

Given this error seems to affect only certain systems additional testers would be welcome.

**Comment by natankeddem** [comment]
If you can take a quick look in `regedit`, could you double check this is what you are seeing?
```
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\.js]
"Content Type"="text/plain"
```
If so I can "break" my PC similarly to test this out. Are you running directly in Windows 10 or using WSL?

**Comment by thetableman** [comment]
> 

I have the issue when using Win 11 directly (no WSL). Confirming that `"Content Type"="text/plain"` for `.js`.

**Comment by rodja** [comment]
This is originally a Windows/Starlette issue which other projects also have build workarounds for: https://github.com/encode/starlette/issues/829

**Review by falkoschindler — CHANGES_REQUESTED** [review]
Thanks for this PR, @thetableman!

I have two questions:

1. Can we move the lines into nicegui.py close to `static_files = StaticFiles(...)`. I think this is the place that actually requires the fix.
2. I think the correct mime type for JavaScript would be "text/javascript" (see https://stackoverflow.com/a/21098951/3419103). Or am I missing something?

**Comment by natankeddem** [comment]
> 2\. I think the correct mime type for JavaScript would be "text/javascript" (see https://stackoverflow.com/a/21098951/3419103). Or am I missing something?


That link states  "text/javascript" is obsolete.

**Comment by natankeddem** [comment]
Nevermind, I it might not be. This RFC confused me https://tools.ietf.org/html/rfc4329

**Comment by natankeddem** [comment]
I was never able to "break" a fresh windows 10 install. I tried adding the key/value to 2 locations per the reports I saw. Perhaps there is more to change but unless @thetableman can't verify i'll pass on digging in further on that.
```
New-PSDrive -Name HKLM -PSProvider Registry -Root HKEY_LOCAL_MACHINE
New-PSDrive -Name HKCR -PSProvider Registry -Root HKEY_CLASSES_ROOT
Set-Itemproperty -path 'HKLM:\SOFTWARE\Classes\.js' -Name 'Content Type' -value 'text/plain'
Set-Itemproperty -path 'HKCR:\.js' -Name 'Content Type' -value 'text/plain'
```

**Comment by thetableman** [comment]
> I just moved the fix to nicegui.py and added a pytest. @thetableman, @natankeddem, can you confirm that it still works on your machines?

Moving `mimetypes` to `nicegui.py` also resolves the issue on my Win10 installation. I also tested with both `application/javascript` and `text/javascript`, both fixed the error I was receiving.

There's a lot of conflicting information about which to use but Mozilla, which nicegui references in other places as a primary source, reads here https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types#textjavascript that `text/javascript` is the current standard. This makes sense as `application/...` suggests a binary file type, which of course javascript is not.

**Comment by falkoschindler** [comment]
Great, thanks @thetableman!
Then let's close this one by merging into main. 🚀

**Pull request merged**
