### PR TITLE
Table: implementation of Quasar's Qtable element

### PR DESCRIPTION
**Pull request by dclause**
This is a second implementation proposition after the PR of @Diegiwg at https://github.com/zauberzeug/nicegui/pull/434

The current implementation is based on his, but allow more use cases and is more simple (IMO). 

It allows: 
- table selection
- table filter
- usage of table slots

The PR provide a basic example in the API reference page, as well as a more detailled example on how to use the table element with slots.

NOTE: It could be completed with some really nice to have scenarios like tables with icons, buttons and anything in rows if we could use props in slots. (see  issue https://github.com/zauberzeug/nicegui/issues/501)

**Todo's following PR review:**
- [x] 1. Move QTr, QTh, QTd to table namespace. Rename to table.row(), table.header(), table.cell().
- [x] 3. Reintroduce the deprecation notice on `ui.table()` and rename this PR `ui.qtable()`
- [x] 4. Remove default arguments for rows and columns parameter: make them mandatory
- [x] 5. Introduce `FilterElement` for the filter prop
- [x] 6. Use `ValueElement`  for selection
- [x] 7. Cleanup newlines added in the PR
- [x] 8. Add `key` attribute mandatory as a column name to unique row data
- [x] 9. Add pagination attribute to control pagination

### CODE REVIEW

**Comment by falkoschindler** [comment]
Thanks a lot for this pull request, @dclause! It looks very promising.
Apart from some details here and there I have some general thoughts. I'll number them for easier reference.

1. Having UI elements `ui.tr` and `ui.td` that only make sense within a table and that have not very meaningful names to non-web developers, made us think about an alternative way to define rows and cells: `table.row()` and `table.cell()`. We did something similar for `ui.scene` (https://nicegui.io/reference#3d_scene), where the `scene` object defines multiple nested classes for 3D objects that should not pollute the `ui` namespace. The result might look like this:
    ```py
    with ui.table(...) as table:
        with table.top_row:
            with table.row():
                with table.cell().props('colspan="100%"'):
                    ui.label('This is a top row').classes('text-center')
    ```

2. Another idea in the example above is to pre-define available slots for easier access. (This is actually something we could also do for other Quasar elements like `ui.input`.)

3. You already replaced `ui.table`, which is currently a deprecated constructor for AG Grids, with the new QTable. But since we deprecated `ui.table` just recently, we might need to keep it pointing to AG Grid for a while. [Here](https://github.com/zauberzeug/nicegui/issues/370#issuecomment-1428065785) I discussed a possible transition using `ui.qtable` for now. What do you think?

4. Why do `rows` and `columns` have default arguments? I think it is ok to make them mandatory.

5. Using the `ValueElement` mixin to hold the filter value is a neat idea. It just might be a bit confusing to have an `on_filter_changed` callback and a bindable `value` property. I'll have to think about it. But if in doubt we can simply create something like a `FilterElement` with a bindable `filter` instead of `value`.

6. We need some concept for updating rows and cells. Properties like `table.rows` and `table.columns` with setters that update `_props` might be a possibility.

7. The diff contains several lines of whitespace in reference.py. It would be great if we can avoid such changes, maybe by finding and committing the necessary IDE settings.

**Comment by dclause** [comment]
Hi !
Thanks for this thorough code review. I love that you use numbered bullet points: that is my way to do too !
I will go though them all to discuss them. Let me add to the PR description the one left to do. I will add the ones I agree with you and the ones where it is a matter of opinion (in that case you opinion wins of course as you are the maintainer). For some points though, I would rather give counter-arguments if you allow me.

1. Sure. Scoping the tr, th and td makes sense. Indeed, those elements exists only in the scope of table and don't make sense in the ui namespace.
I will rename them respectively table.row(), table.header_cell() and table.cell() because that is what you ask : I guess it is a matter of opinion, but I would suggest not to. Indeed people who don't know html would have to learn th, td and tr but that would teach them something everyone knows. While learning about cell, row and header_cell would require people that already know HTML to learn a new API that no one knows about for it is specific to that project. I would rather suggest to leave it table.tr(), table.th(), table.td(). 
2. Let me disagree here. The API of nicegui is really elegant : want a new Quasar element ? Just create a class extending Element and the q-xxx name and that's it. We don't add each Quasar property to that class, they are accessible via props(). In the same way, we don't add each slots too, they are accessible via add_slot(). Doing so would bind much more nicegui to a specific version of Quasar. If you update Quasar tomorrow, you will have to loop through all elements in the project and check / update the slots and properties. Plus, as a developper, if you want to use a slot, you would have to go to Quasar documentation, find the slot, then go to nicegui documentation and find the equivalent API. That is an extra step that just adds noise on my opinion. If you know Quasar here, you just have to use add_slot() and that's it. Nothing else to check: the API of nicegui is frictionless here.
3. Arguably, the more we wait, the more people adopt the project, the more people will have to change their code from ui.qtable() to ui.table(). I would suggest to go for ui.table() now because table() follows the rest of convention of the project (new adopter won't understand why suddently this element as a q-prefix) and people will certainly use QTable more than aggrid because that goes with the rest of the design and it does not involves an extra framework. I would even say that aggrid is redondant to QTable and I would go further and suggest removing completely aggrid IMO (which means deprecate it first for a while). I will stand with your decision here though, let me now if I rename to qtable.
4. Totally agree
5. I thought about it, and did not go with the `FilterElement` because I was afraid to add an extra class that invites for reusability when table was the only place for this. But thinking about it, that would let other element to potentially become filtrable (QTree?). Also, I have played with the PR for my own project and I felt like rows should be reactive too. I wanted to use `bind_value(self, rows)` for my rows and the filter would make sense to have a `bind_filter`. So let's go with a FilterElement here with bind_filter.
6. How about using the `bind_value` from `ValueElement ` for the rows ? As I played with the PR I found it necessary to update my rows. However, I would recommand not to do it for columns. As a developper, you can do it yourself with props and `.update()` and that would be a specific use case like an "add a column" button. Changing the whole table structure dynamically and transparently would encourage layout shift on the page which is hard to handle in terme of design and is annoying for the user. Would you agree with this ?
7. owww... my bad, I will try to clean that.

**Comment by falkoschindler** [comment]
Thanks for your valuable feedback! You have some good points here. 😀
Let me address some of them before you start changing the implementation:

1. Sticking with the existing and well-documented Quasar API is an absolutely reasonable goal. On the other hand, we try to make NiceGUI accessible for new developers that are not familiar with the underlying libraries. So I'm a bit undecided.

2. That's an interesting topic. I think with NiceGUI's generic string-based API we made a good decision. But recently we started thinking about creating more and more native APIs to access CSS, Tailwind and Quasar features (#117, #362, #364). Some users wished for a more discoverable UI without the need of having a Tailwind and Quasar documentation at hand all the time. But since we use strings for other Quasar slots, I would agree with you and leave it this way for now. As a minor improvement we could overwrite `add_slot` with a `Literal` type annotation so that the IDE can auto-complete available strings. Of course, this needs to get maintained when upgrading Quasar, but a wrong annotation wouldn't harm too much.

3. Somehow I thought we should stick to a more conservative deprecation timeline, since we already have quite a number of users. But the argument to better break an API now than later is very appealing!


6. I'm a bit sceptical binding will work well for arrays. That's why we didn't use it for the `options` in `ui.chart` or `ui.aggrid`. Users might simply append new elements, which the binding module won't notice because the reference is unchanged and the property setter is not called. But I'm open for ideas! Maybe there is an elegant binding-like solution I've been missing.

@rodja I'd like to hear your opinion, especially about points 1, 2, and 3.

**Comment by rodja** [comment]
### 1. table.td, tr, th vs table.data, cell, header

> people who don't know html would have to learn th, td and tr but that would teach them something everyone knows. While learning about cell, row and header_cell would require people that already know HTML to learn a new API that no one knows about for it is specific to that project

With NiceGUI we want to present users with the nicest possible API. This can be similar to HTML or Quasar but should not be weighted in as an argument. Instead of similarity to existing APIs we should think about what is intuitive. In my opinion `table.tr` is a very good example of what we should not do. Abbreviations like `tr` have very little meaning if you do not know html and are not easy to speak which is quite important for commination between developers. Instead of "teaching" users how html works, we should pave the way for everyone with as much usability as possible. Also "table table row" is quite redundant. Therefore I would go with table.row and table.header. If we picked table.cell over table.data because "data" is such an empty word. And if you cut rows with columns you get cells. And thats where the user should put the elements.

### 2. generic add_slot(...) vs auto-completion

I also thought about our efforts and discussions in #117. It's much nicer if we could provide suggestions (ideally with documentation) for the available API. This makes NiceGUI much more discoverable. It simply removes the friction of having to look up magic words on some website. We do not need to remove the generic `add_slot(...)` function but rather provide the auto-completions on-top. In this particular case I would favour functions over Literals because we can add extensive documentation which will be presented by the IDEs.

### 3. ui.table vs ui.qtable

I like the simplicity of ui.table. ui.qtable is not "nice". Especially if we want users to use this as their new default. But Quasar also has a simple table: https://quasar.dev/vue-components/markup-table#introduction. If we embed this, will it be ui.simple_table? Or should we do it similar to ui.image and ui.interactive_image, where the more feature rich element has the more complicated name? What would that be for the q-table wrapper? ui.interactive_table?

**Comment by dclause** [comment]
OK: Added (1) => renaming to the todo list. I added your suggestion @rodja : 
create a QTr -> `.row()`
create a QTd -> `.cell()`
create a QTh -> `.header()`
I would argue though that `.header()` is not very explicit as it sound like a whole header row rather than a cell which <th>.

Also added (3) => reintroduce the deprecation notice on `ui.table()` and rename this PR `ui.qtable()`

As of number (2), well... I guess that makes a noisier API as I explained. But anyway, I suppose this would be out of the scope of this PR as this kind of decision would impact every other component does it ?

**Comment by falkoschindler** [comment]
1. I also think `header_cell` is the better name.
2. I would prefer to keep it out of this PR. In my point of view, the new API for pre-defining slots it not yet totally clear. (E.g.: Do we create slots like `table.top_row` in the initializer, or do we provide functions `table.top_row()` that create these slots on demand?) Therefore I'd like to give it a bit more time. It is not needed for this PR and the decision process would unnecessarily hold back its merge.
3. Here I'm also not completely sure. @rodja Let's talk about this once again this week to finalize the naming.

**Comment by falkoschindler** [comment]
I created https://github.com/zauberzeug/nicegui/discussions/522 for thinking about an improved slot API.

**Comment by dclause** [comment]
Point 8 should be added: a key to a unique column name must be provided. Many functionality (include sort, search, filter, ...) won't work properly if a unique 'row-key' attribute is not given to the QTable. By making it mandatory, I think that makes using the props() and selection much more transparent for the user.

**Comment by dclause** [comment]
Point 6: ValueElement does not make sense here. Instead, I have expanded the example with how to add/remove rows dynamically.

Point 9: add a parameter to control the number of items per page in pagination (None to hide, 0 for all, int for a specific number)

**Comment by dclause** [comment]
I think I'm done adding corections for your feedbacks here.
Let me know :)

**Comment by rodja** [comment]
@dclause you convinced @falkoschindler and me to break the API early and go with `ui.table` for the next release. This of course mean that we will use 1.2.0 as a version number and implies that we update Quasar and similar libs to the latest stable versions (see #318).

**Comment by falkoschindler** [comment]
@dclause I reviewed your code again and spent some time with it. There turned out to be still some issues with the row selection. It was easiest for me to directly play around with the implementation and push my changes to the PR.

1. The `ValueElement` turned out impractical for row selection. Firstly, it's because the `selected` event doesn't send the complete new selection, but only the rows that changed state. Therefore multiselection did not work as expected. Secondly, binding lists is a bit unintuitive. If we provide methods for binding a `selected` list, one would expect an automatic UI update if this list changes. But the binding mechanism doesn't recognize changes as long as the reference remains the same. Oh and thirdly, by deriving from `ValueElement` we introduce methods like `bind_value`, which has no intuitive meaning in the context of a table. Long story short, I simply introduced a normal `selected` list and an optional `on_select` callback with `TableSelectionEventArguments`.
2. In consistency with `ui.tree` I set the default value for `row_key` to Quasar's default "id".
3. I replaced the selection option `'none'` with `None`.
4. I replaced the parameter `pagination` with the more descriptive `rows_per_page` with the default value `None` to hide it by default.
5. Since `add_row` and `remove_row` might be handy for many applications, I moved them into the table class.
6. As @rodja already mentioned, we aggreed to replace `ui.table` with this new QTable right with the next release.
7. Last but not least, I added some pytests for `ui.table`.

**Comment by dclause** [comment]
@falkoschindler wow nice additions ! I will read your code tomorrow but I have already read your commented points.
The only one that triggers me is the point 4: 
`rows_per_page` set to None disables the pagination while 0 means a pagination is there but with All rows visible by default. I feel like the variable name may not reflect properly that does it ?

However, just a little typo, the documentation state the default value of rows_per_page is 0 while it's actually `None`. I guess that is just the comment to update.

**Comment by falkoschindler** [comment]
@dclause Yes, you're right. Using the more general parameter name `pagination` might be the better choice, considering the possible value `None`. I changed it accordingly. And I also fixed the documentation.

**Comment by dclause** [comment]
Hi! I read at your modifications: way better indeed ! 
I have pushed this morning a simple test to check for named slot and scope slot in the test_table.py file if you want to have a look at it.
Otherwise the PR seems complete now, is it ?

**Comment by dclause** [comment]
Thanks for clean up. Does it need some indentation of q-td inside the q-tr on the "vuejs" template section ?

**Comment by falkoschindler** [comment]
Oh yes, I fix the indentation. Not crucial at all, but once we are at it...

**Comment by dclause** [comment]
Indeed ! 
Do you need anything else from me for this PR to be merged ? Are we done on the subject here ?

**Comment by falkoschindler** [comment]
Yes, we can merge this PR. Thanks again for your great contribution, @dclause! It's a pleasure working with you. 😊

**Comment by Shahin-rmz** [comment]
Hello, I can write the documentation about the table if you like.
But I am not sure how it works at all BTW.

**Comment by falkoschindler** [comment]
Thanks, @Shahin-rmz! But there is already some documentation written in [table.py](https://github.com/zauberzeug/nicegui/blob/main/nicegui/elements/table.py). It will be published on nicegui.io as soon as NiceGUI 1.2.0 (including the new `ui.table`) gets released.

**Pull request merged**
