### PR TITLE
Allow canceling a timer

### PR DESCRIPTION
**Pull request by falkoschindler**
As requested in #1477, this PR adds the possibility to cancel a timer.
This stops the infinite while loop. Afterwards the timer cannot be activated again.

### CODE REVIEW

**Comment by bergmansj** [comment]
Looks good. Thanks for picking this up so quickly 👍

**Comment by rodja** [comment]
@falkoschindler I would like to use `.remove()` instead of `.cancel()` because it better carries the information of not being able to resume it.

**Comment by falkoschindler** [comment]
@rodja First I chose `.stop()`, but then went for `.cancel()` to indicate the destructive nature of this method. I'm not sure about `.remove()`, because it suggests a similarity to an element, which the timer isn't. But I'll think about it once more.

**Comment by rodja** [comment]
Ok. `.remove()` is to close to elements. I thought about `.abort()` but that is very similar to `.cancel()`. So we can go with it, I think.

**Comment by natankeddem** [comment]
I like`.destory()` if you guys are taking suggestions. It seems fairly popular with some JS libraries.

**Comment by rodja** [comment]
Cool @natankeddem. I'm also in favour of `.destroy()` because it hints at the internal `._cleanup()` method which releases the `.slot` and `.callback` members. The object is practically unusable after calling.

**Comment by falkoschindler** [comment]
I was about to push a commit renaming `cancel()` to `destroy()`.

But the demo feels weird:
The title "Activate, deactivate and cancel a timer" becomes "Activate, deactivate and destroy a timer"
And the "Cancel" button becomes a "Destroy" button.

Other example: In a code-review, would you really say "Oh, we need to destroy the timer when the user clicks this button"? I think I would _say_ "cancel" even though I would be writing "destroy". That's not a good sign.

**Comment by bergmansj** [comment]
In async frameworks tasks that are interrupted before finishing and in general cannot be resumed, the term 'cancelled' is used.

**Review by rodja — APPROVED** [review]
I'm now convinced `.cancel()` is the right name for it.

**Pull request merged**
