### PR TITLE
doc add vertical tabs example

### PR DESCRIPTION
**Pull request by youyou015**
Create vertical tabs need combine with other elements to make it, so I think it's worth to add one example in the documentation.

### CODE REVIEW

**Comment by falkoschindler** [comment]
Thanks for the pull request, @youyou015! Showing a vertical tabs demo is certainly a good idea.
I just wonder why you use a `ui.splitter` instead of, e.g., a `ui.row`. It is an interesting application, but not the simplest way to use vertical tabs.

**Comment by youyou015** [comment]
> Thanks for the pull request, @youyou015! Showing a vertical tabs demo is certainly a good idea. I just wonder why you use a `ui.splitter` instead of, e.g., a `ui.row`. It is an interesting application, but not the simplest way to use vertical tabs.

@falkoschindler  Haha, you're right, just checked that using `ui.row` is also work, I haven't though it before😂. Using `ui.splitter` is inspired from Quasar's vertical tabs example (https://quasar.dev/vue-components/tabs#vertical) that I mentioned in the demo description, anyway, use it can have benefit for draggable. Do u think I should change it to `ui.row`?

**Review by falkoschindler — APPROVED** [review]
Ah, I see! Let's keep the splitter. 🙂
I even updated the demo with icons and a little more content from the original example.
Let's merge!

**Comment by youyou015** [comment]
Great!

**Pull request merged**
