### PR TITLE
introduce ui.dark_mode

### PR DESCRIPTION
**Pull request by falkoschindler**
This PR proposes a `ui.dark` element that can be placed anywhere on the page an allows to easily get, set and bind the dark mode like this:

```py
dark = ui.dark(True)

ui.button('Dark', on_click=dark.turn_on)
ui.button('Light', on_click=dark.turn_off)
ui.button('Auto', on_click=dark.auto)

ui.label().bind_text_from(dark, 'value', backward=lambda x: f'Dark mode: {x}')
```

Let's discuss the overall approach before adding tests and documentation.

---

- [x] rename to `ui.dark_mode`, `enable()`, `disable()`
- [x] add `toggle()`
- [x] fix page test
- [x] write dark_mode test
- [x] write documentation

### CODE REVIEW

**Review by rodja — COMMENTED** [review]
Great work. I'm a bit undecided about the `turn_on` and `turn_off` function names. Maybe `ui.dark_mode.on()` and `ui.dark_mode.off()` would be better? A `ui.dark_mode.toggle()` would also be handy.

**Comment by falkoschindler** [comment]
@rodja Well, I ran into conflicts with `Element.on()`...
Do you prefer `ui.dark_mode` over `ui.dark`?

**Comment by rodja** [comment]
@falkoschindler I lean towards `dark_mode`. But it depends on the function naming, I guess. What do you think about `dark_mode.activate()` and `dark_mode.deactivate()`?

**Comment by falkoschindler** [comment]
We agreed on `dark_mode.enable()`, `dark_mode.disable()`, `dark_mode.auto()` and `darkmode.toggle()`.

**Review by rodja — APPROVED** [review]

**Pull request merged**
