### PR TITLE
#2549 feat: added build package script

### PR DESCRIPTION
**Pull request by gotev**
@falkoschindler added the script as per your instructions in #2549. The script is meant to be copied and used as a base package build script for nicegui users, who will need to also modify it for their own specific usage (e.g. adding resources, icons and so on)

### CODE REVIEW

**Review by falkoschindler — COMMENTED** [review]
Thank you for the pull request, @gotev!

I just reviewed the code and refactored it a bit to organize common and platform-specific arguments more intuitively. And I introduced argparse to allow configuring the parameters from outside.

What do you think so far?

I wonder if we really need to call `pyinstaller` without `python -m` on Windows... And what's the reason for the extra `--onedir`? There might already be an explanation in one of the issues and discussions, but I honestly lost track of every detail. Good to have this script to capture them all! 🙂

**Comment by falkoschindler** [comment]
@gotev You're right, we should be careful not to suggest or promise to wrap PyInstaller in all its glory, but to only give a starting point from which our users can deviate. I just thought it would be nice to have an executable documentation for how to package a NiceGUI app that is actually shipped with the library and which you can simply call for simple use cases.

(In the future) we can use it to guide the user to the most important arguments to consider and include some [hints](https://nicegui.io/documentation/section_configuration_deployment#package_for_installation), either in the help text or in form of console output, like "1. Make sure to set native=True...", "2. Note about packaging on macOS: ..." and so on.

Regarding the `--add-data` argument: It should already work as expected, i.e. `nicegui` is always added while you can additional data:

```bash
$ ./pack.py --add-data /foo --add-data /bar --dry-run main.py
python -m PyInstaller --name Your App Name --add-data /Users/falko/Projects/nicegui/nicegui --add-data /foo --add-data /bar --windowed main.py
```

**Comment by gotev** [comment]
Got it, so let's proceed then. If we have a way to validate what the user is passing in `ui.run` before starting the packaging, it will be great, so we could simply fail the build printing out messages like `native=True is required` and so on.

Another useful thing we could add is to print out the full PyInstaller command before executing it, so it's clear we're providing a helper rather than a wrapper, reducing frictions for simple use cases and already giving the starting command for more complex scenarios.

**Comment by falkoschindler** [comment]
I like the idea of always printing the command!
Detecting whether `native=True` is set could be challenging though. Users could make it dependent on some other flag like `native=PRODUCTION`, so that scanning for the string "native=True" is not enough. But we can postpone this feature and just print some short info text for now.

**Comment by gotev** [comment]
Agreed!

As an idea to achieve that, we could detect if the app is running inside a pyinstaller package at runtime:

```python
def is_pyinstaller():
    return getattr(sys, 'frozen', False) or hasattr(sys, '_MEIPASS')
```
and validate run params. But that's for another PR 😉

**Comment by falkoschindler** [comment]
I just looked into this PR and noticed some remaining points we need to address:

- [ ] Regarding our idea about checking for `native=True`: The [documentation](https://nicegui.io/documentation/section_configuration_deployment#package_for_installation) recommends using `--windowed` only with `native=True`. Conversely, we don't need `native=True` if `--windowed` is not set. So I wonder if we really should set `--windowed` by default. Maybe we don't set it, but add a new argument `--windowed` for pack.py with a description taken from the NiceGUI documentation.

- [ ] Same for `--onefile`: We should add it as an argument with a description from the NiceGUI documentation.

- [ ] We should add the remaining packaging tips to the help text.

- [ ] We should warn about not packaging with `reload=True`.

**Comment by falkoschindler** [comment]
Ok, I added some more documentation to the pack.py script. Let's merge and improve it later.

**Pull request merged**
