### PR TITLE
Pytests with Selenium

### PR DESCRIPTION
**Pull request by rodja**
Begin writing tests with selenium headless browser.
This pull request is only meant as a starting point do find a first suitable API and infrastructure.
The test coverage should be increased after merging.

### CODE REVIEW

**Comment by rodja** [comment]
I think the integration into the GitHub Action workflow should also be done in a separate pull request. It's valuable in itself when executed locally.

**Comment by falkoschindler** [comment]
On my machine only 2/5 tests are green when executing all at once. When running them individually, they are all green. It looks like the global state is not reset correctly:

```
...
  File "/Users/falko/Projects/nicegui/nicegui/page.py", line 230, in init_auto_index_page
    page: Page = get_current_view().pages[0]
KeyError: 0
```

**Comment by rodja** [comment]
@falkoschindler Yes, this is work in progress.

**Comment by rodja** [comment]
@falkoschindler after adding a fixture which resets the globals before each test run, all tests are now passing.

**Comment by rodja** [comment]
I'll keep using this branch to investigate the remaining issues of #85 until it's merged. This has just uncovered another "global reset" problem in the test infrastructure (see https://github.com/zauberzeug/nicegui/pull/88/commits/38b6b6d27bf7d88a61487f1f9e03059e64f6b146).

**Pull request merged**
