### PR TITLE
Website ui.input demo not rendering.

### PR DESCRIPTION
**Pull request by natankeddem**
This is a fix for the ui.input demos not rendering correctly that I brought up in this issue: https://github.com/zauberzeug/nicegui/issues/1616

I removed the async from these demo functions. I might be missing something as to why they are there in the first place? I don't see any other documentation demo functions utilizing async.

### CODE REVIEW

**Comment by natankeddem** [comment]
@rodja just to be candid my modification to the demo functions might just be a bandaid specific to `ui.input`. After looking more into this it looks like the intention is to have some demos be async https://github.com/zauberzeug/nicegui/commit/f3bbfa8a14f6c40bfdaa9a8da46d76304e860cf8. After searching there do appear to be more demos that are; and they to appear to be broken as well. Although, I don't see a reason to have these `ui.input` demos be async the others probably have legitimate reasons to be.
image

**Comment by rodja** [comment]
Wow! This is bad. Glad you both took the time to dig into this. @falkoschindler do you have an idea on how to best approach this?

**Comment by natankeddem** [comment]
There is only the one of me here. :smiley:

**Comment by natankeddem** [comment]
I was able to fix the problem but I doubt it is optimal, I think it is still a bandaid to lower level issue possibly. There appears to be issues when an async `f()` is contained in a tuple and passed to an event handler.  I need to spend some more time learning how tuples passed to events work.
demo.py:
```py
        with browser_window(title=getattr(f, 'tab', None),
                            classes='w-full max-w-[44rem] min-[1500px]:max-w-[20rem] min-h-[10rem] browser-window') as window:
            spinner = ui.spinner(size='lg').props('thickness=2')
            intersection_observer(on_intersection=lambda: window.remove(spinner))
            intersection_observer(on_intersection=f)
```

**Comment by falkoschindler** [comment]
Wow, thanks a _ton_, @natankeddem! What a catch!

First of all: It doesn't make sense to mark these demos as async, since they should definitely run synchronously. They are presented to the user as synchronous code after all. But from time to time an `async def` appeared by accident (not sure how this actually could happen so often) and hasn't been spotted (or ignored) during code review (my bad).

Now the interesting part: This didn't use to be a problem, since the demo function is executed by the event handler of the intersection observer. And since NiceGUI's event handlers automatically await async callbacks, these async demo functions haven't been a problem. But three weeks ago I added a tiny spinner that needs to get removed once the intersection observer executes the demo function (https://github.com/zauberzeug/nicegui/commit/f253d9f3de4ee816281496426c9627ccecda09e2). Unconventionally I simply put the `window.clear()` and the demo function `f()` into a tuple, which works for synchronous functions. But not if one of them is async!

So there are two approaches, and maybe we should do both - just for robustness?

1. Remove the `async` declaration from all demo functions.
2. Split up the `on_intersection` tuple (in case an `async sneaks in in the future).

**Comment by natankeddem** [comment]
It sounds like the event tuple interaction I saw was expected. I will stop digging deeper into that. It also sounds like me splitting the spinner removal and demo execute was sane after all. I'll try to put out some commits into this PR in the next day or so.

**Comment by natankeddem** [comment]
I believe I have captured the split of `on_intersection` and removal of some of the unneeded async demos. There are a few more async demos which I need to take a closer look at and verify removing the async will not break anything.

**Comment by natankeddem** [comment]
I also fixed a few lint issues that I noticed while in these demo files. There are 2 demos which appear to require async; perhaps there is a way to refactor them to not require it but it wasn't anything simple:
- button -> `await_button_click`
- generic_events -> `custom_events`

**Review by falkoschindler — APPROVED** [review]
@natankeddem Oh I see! I already had a strange feeling when I wrote "they should definitely run synchronously". Indeed there are demos with some trickery that need to be awaited. But by fixing the intersection handler this is alright.

I just changed the event registration a little to avoid the need for two intersection observers per demo. It's a bit longer though, but more efficient in terms of bandwidth.

Anyway, I think this PR is ready to merge!
Thanks again for your contribution, @natankeddem!

**Comment by natankeddem** [comment]
So, that's how you put `f` inside of a nested function! I was pulling my hair out asking why it wasn't working. Thanks for showing me something new. You are welcome for the PR, it was a pleasure.

**Pull request merged**
