### PR TITLE
Introduce ui.get to query the element tree

### PR DESCRIPTION
**Pull request by rodja**
Originated in https://github.com/zauberzeug/nicegui/discussions/1923#discussioncomment-7419532, this PR introduces `ui.get` to retrieve elements of the current page with a query language inspired by tortoise-orm's `filter` or BeautifulSoup's `find_all`. Therefore it also introduces a ~~`.tags`~~ `.keys` property on Element with wich the developer can set a list of queryable words.

When complete this PR should allow these kinds of operations:

```py
buttons = ui.get(type=ui.button)
headers = ui.get(key='header')  
action_buttons = ui.get(type=ui.button, key='action')
buttons_with_text = ui.get(type=ui.button, text='Click me')
buttons_witout_text = ui.get(type=ui.button).without(text='Click me')
buttons_within_header = ui.get(type=ui.button).within(key='header')
buttons_within_header_or_footer = ui.get(type=ui.button).within(key=['header', 'footer'])
```

The object which is returned by `ui.get` is called `Elements` (eg. group of elements) and allows setting props,classes,style on all containing elements at once:

```py
ui.get(key='important').classes('text-bold')
```

And it allows iterating over all elements:

```py
for element in ui.get(key='important'):
    print(element)
```

If `type=` is used the iterator automatically casts to this type:

```py
for stepper in ui.get(type=ui.stepper):
    stepper.next()
```

# ToDos

- [x] `type=`
- [x] iterating with typing
- [x] .classes
- [x] .style
- [x] .props
- [x] `text=`
- [x] `key=` and `.keys`
- [x] `.within(type=`
- [x] `.within(key=`
- [x] `.exclude(type=`
- [x] `.exclude(key=`
- [x] `.exclude(text=`
- [x] `.not_within(type=`
- [x] `.not_within(key=`
- [x] `.key` with string or List
- [ ] ~~`.type` with class or List~~ [simplify usage of Mixins](https://github.com/zauberzeug/nicegui/pull/1931#issuecomment-1788420084)
- [x] `.text` with string or List
- [ ] docstrings
- [x] documentation_get.py with demos
- [ ] looking through the examples and checking where `ui.get` would make sense
- [ ] discuss general impact on maintenance etc.

### CODE REVIEW

**Comment by ed2050** [comment]
Thanks @rodja, this looks like a great start.

# Questions
1. What are tags in this system?  Is it a new free-form id as in #1923?  Users can set to any value they want?  What are the identifier rules, \w+?
2. Can elements have just one tag or several?
3. Is there a way to update tags after element creation?  I find this to be a general issue across nicegui.  Parameters like icon= seem to be set-and-forget with no apparent way to change them later (or maybe I missed it).
4. The Elements return value: when it iterates over elements, do we get the actual element or a proxy?  I want to access more than just styles / props / classes.  I want full access to the element so I can call move(), disable(), update source=, etc.  If it's a proxy, then it should at least contain a reference to the underlying object.  Like:
```
for proxy in ui.get (type = 'ui.button') :
    proxy.classes ('text-bold')
    element = proxy.element   # access to full element
```
6. Not sure I understand the stepper example.  What are you saying about type= iterators?

# Other comments
I'll also point out that tags can be a bit confusing, since elements ultimately render to html tags.    Maybe the parameter could be called ntags (niceguitags) or utags (user tags) or otags (object tags) or something to better distinguish.  I would suggest labels but you already have ui.label.

I know you don't want users to have to know html to use nicegui, and that's fine.  But a large portion of programmers do know html.  Any serious nicegui users will eventually run into html & css issues.  Avoiding html terms is helpful to reduce confusion.  If you don't know html then it doesn't matter what you call it, labels or tags or names work equally well.

Hope this helps.  Looking forward to this development! 😃

**Comment by rodja** [comment]
Thanks for the comments and questions @ed2050.

You are right. The name "tags" is not optimal. We need to find something else. Ideally it should not be cryptical like ntags or so. Maybe "markers"? 

Questions 1-3: The idea is that it works like classes. You can define multiple and change them on the fly. But they are not interpreted by the browser and hence can be used without clashing with existing quasar/tailwind classes.

Question 4-6: As you can see in the tests you have the "real" NiceGUI elements, when iterating over the `Elements` group (and the items have the correct type hints, if you use the `type=` parameter): https://github.com/zauberzeug/nicegui/blob/f7235abe1f82275831eba5bbbefa3d67d2bb5c7f/tests/test_get_elements.py#L33.

**Comment by ed2050** [comment]
Fantastic.  I suspected as much, thanks for verifying.

Possible names:
- markers
- marks
- names
- flags
- userids (or uids)

Acually I think `labels` is the best fit.  `ui.label` doesn't seem to be a particularly descriptive name for a text component; ui.text would be more natural.  But I suppose it's too much hassle to change now.

After that my next choice would be marks.  Names has possible confusion with html (both tag "names" aka h1,img,body, etc or occasionally name= attributes).  Tags is a better fit, unfortunately overlaps with html.  Userid suggests single unique values, and flags are usually boolean.

That said, any of the above would work.  My preference is for shorter names, but any will do.

Thanks @rodja.

**Comment by rodja** [comment]
I also like `.labels`. We already have the ongoing discussion about renaming `ui.label` into `ui.text` in https://github.com/zauberzeug/nicegui/discussions/1805.

**Comment by rodja** [comment]
After some discussion about the naming with ChatGPT 4, it came up with this rating:

- Attributes: ★★★★☆
- Keys: ★★★★☆
- Labels: ★★★★☆
- Identifiers: ★★★☆☆
- Tags: ★★★☆☆
- Marks: ★★★☆☆
- Markers: ★★★☆☆
- Categories: ★★☆☆☆
- Flags: ★★☆☆☆
- Traits: ★★☆☆☆
- Descriptors: ★★☆☆☆
- Metadata: ★★☆☆☆
- Names: ★★☆☆☆
- Userids (or uids): ★☆☆☆☆

I'll go with `.keys` for now because its short and does not clash with existing `ui.label`. Also I want us to get a feel on how  problematic the term overlap with "keys" in a Python dict is.

**Comment by rodja** [comment]
When I started implementing `ui.get(type=[ui.button, ui.text])` I realized that this is probably not a good idea because we would loose typing in the iterator. Then I discovered that this is already working:

```py
    from nicegui.elements.mixins.text_element import TextElement

    ui.button('button A')
    ui.label('label A')
    ui.icon('home')
    ui.button('button B')
    ui.label('label B')

    result = [b.text for b in ui.get(type=TextElement)]
```

So we only need to think if we want to make the mixins better acessable or not.

**Comment by rodja** [comment]
I think

https://github.com/zauberzeug/nicegui/blob/d38671df5f5f55a278d8b2f4bf266c6e1c67503f/website/style.py#L76

from the documentation structure rewrite in #2084 is a good example where `ui.get` would simplify things.

**Comment by falkoschindler** [comment]
I'll close this PR in favor of PR #3121.

**Pull request closed without merging**
