### PR TITLE
Improve interaction with Matplotlib

### PR DESCRIPTION
**Pull request by tacaswell**
This PR is mostly a feature request/suggestion but it was easier to describe it via code that in text.  So here is a draft PR (rather than an issue with an inline diff).

----

This is a sketch of how to improve the interaction with Matplotlib.

The first idea is to directly create `Figure` objects rather than relying on pyplot.  This de-couples the UI from the global state that is the pyplot figure registry and ensures that you never get surprise GUI windows popping up (or a memory leak) when pyplot selects a GUI backend.

The second suggestion is to have the object return by the context manager be able to create multiple figures (not actually implemented).

The third is to support saving the figures as png instead of svg (not actually implemented).

### CODE REVIEW

**Comment by tacaswell** [comment]
https://github.com/matplotlib/mpl-gui?tab=readme-ov-file#motivation is a slightly longer explanation, but the core of it is that is a bunch of global state you do not need and runs the risk of starting up a GUI event loop that (may) allocate memory that will only be release when the event loop is run (but you never run the event loop!).

The usage would look something like:


```python
with MplFigure(fmt='png') as fig_factory:
   fig = fig_factory.figure()
   ax = fig.subplots()
   # ax.....
   fig2 = fig_factory.figure()
   ax2 = fig2.subpots()
   # ax2....

```

**Comment by tacaswell** [comment]
1. if you end up on a system where the automatic backend picks a GUI backend you may end up with objects that can to be fully garbage collected until you run the GUI event loop (even though you have a bunch of logic to make sure that you close the figure with `pyplot`)
3. Fundamentally, `pyplot` is a bunch of helper functions to make working in an interactive prompt easier and are not a good fit for writing libraries on top of.  If you do not use pyplot you can drop the `_auto_close(...)` logic because there would be no global state so the Matplotlib objects would be cleaned up in normal order as would any other  Python object.
4. if the users pass `num=...` which gets passed through to `plt.figure` then they user will be able to get the same instance in multiple places.  Maybe this is desired, but I suspect it is more likely it will cause problems if multiple handlers are running at once (not 100% sure that is possible as I have not traced all the asnyc details).

Put the other way, it is not clear to me what benefit you are getting from `pyplot`.

**Comment by falkoschindler** [comment]
I just updated the code to reflect the new API
```py
with ui.matplotlib(figsize=(3, 2)) as fig:
    ...
```
There's one issue though: A UI element is supposed to return itself when entering its context. But here we return an MPL figure, which causes a type error. Maybe we need to change it to
```py
with ui.matplotlib(figsize=(3, 2)) as mpl:
    fig = mpl.figure
    ...
```
or
```py
with ui.matplotlib() as mpl:
    fig = mpl.figure(figsize=(3, 2))
    ...
```
or simply
```py
fig = mpl.Figure(figsize=(3, 2))
ui.matplotlib(fig)
```

The latter is more in line with `ui.plotly`. Since we don't need to build the figure inside some context like with pyplot, we can create it independently and pass it to the UI element.

**Comment by falkoschindler** [comment]
@rodja I finished the new `ui.matplotlib` element. In contrast to our earlier idea we _need_ the figure context to know when up update the rendered HTML.

Now this is the new usage compared to `ui.pyplot`:

```py
import numpy as np
from matplotlib import pyplot as plt

from nicegui import ui

x = np.linspace(0.0, 5.0)
y = np.cos(2 * np.pi * x) * np.exp(-x)

with ui.pyplot(figsize=(3, 2)):
    plt.plot(x, y, '-')

with ui.matplotlib(figsize=(3, 2)).figure as fig:
    fig.gca().plot(x, y, '-')
```

Note how `ui.matplotlib` doesn't need any imports other than `ui`.

**Comment by falkoschindler** [comment]
@tacaswell Here I explained the problem: https://github.com/zauberzeug/nicegui/pull/2553#issuecomment-1978135827

**Comment by tacaswell** [comment]
Ah, sorry for the noise (and my failure to re-read the full thread).  That makes sense.

**Review by rodja — APPROVED** [review]

**Pull request merged**
