### PR TITLE
allow binding source with local file paths

### LINKED ISSUE #1853: ui.image() source does not auto-create route to local image when using binding
### Description

```py
a = { 'a': '/home/kon/Pictures/DSC06478.JPG'}

ui.image().bind_source_from(a, 'a')
```

Will throw error:
```
http://127.0.0.1:8080/home/kon/Pictures/DSC06478.JPG not found
```

Same is true if source is set with `img1.source = some_local_path`.

### PR DESCRIPTION
**Pull request by rodja**
This PR fixes #1853 by checking weather to create a route to local file whenever the image source changes.

### CODE REVIEW

**Review by falkoschindler — CHANGES_REQUESTED** [review]
As already discussed in #1282, this approach creates a memory leak if auto-generated routes are not cleaned up. Especially when streaming image sequences this might accumulate quickly.

Since fixing #1282 and #1853 is not crucial for 1.4, I'd postpone it to 1.4.1 and focus on the more critical issues for now.

**Review by falkoschindler — APPROVED** [review]
@rodja I implemented the auto-removal of generated routes, including dedicated pytest for this matter. From my point of view this PR is finished. You can have a look and merge it if the tests are green and you approve the changes.

**Comment by falkoschindler** [comment]
I don't get it. The test `test_removal_of_generated_routes` works in isolation, but not in succession with the other tests in `test_image.py` somehow there are still routes from the previous test and I don't find a way to remove them.

I tried something like
```py
    for route in list(app.routes):
        if route.path.startswith('/_nicegui/auto/static/'):
            app.remove_route(route)
```
in conftest.py or in the test itself, but it doesn't work.

**Comment by rodja** [comment]
@falkoschindler `app.remove_route` expects a path to a route, not a route.

**Pull request merged**
