### PR TITLE
#287 Text input example drops keys

### PR DESCRIPTION
**Pull request by FI-Mihej**
Fix for https://github.com/zauberzeug/nicegui/issues/287 (Text input example drops keys)

### Main idea

1. Components like ui.input do not need a loopback from the server (with `Element.update()` method) by default. They are updated on a browser side instead. At the same time, server still get an update events and can react with an event handler (as usual). If some item must be locked to server-only reaction (made by an event handler) - that item should be created with a `only_serverside_react=True` parameter. For example:

`ui.switch('Switch', on_change=lambda e: output.set_text('Switched on' if e.value else 'Switched off'), only_serverside_react=True)`

2. If developer wants to turn on server-side loopback for the item (automatic `Element.update()` call on the item's state change from the browser side) in order to return an original behavior for some reason - they can set `server_side_loopback=True` parameter:

`ui.switch('Switch', on_change=lambda e: output.set_text('Switched on' if e.value else 'Switched off'), server_side_loopback=True)`

3. Throttling can now be set per item:

`ui.switch('Switch', on_change=lambda e: output.set_text('Switched on' if e.value else 'Switched off'), throttle=0.05)`

> Those three parameters above are independent from one another.

4. An "update" tasks will be executed in the same order as an appropriate incoming events. See changes in `nicegui/element.py`

### Affected components for [1 - 3]

Subset of classes derived from the ValueElement:

- Checkbox (ui.checkbox)
- ColorInput (ui.color_input)
- Input (ui.input)
- Number (ui.number)
- LinearProgress (ui.linear_progress)
- CircularProgress (ui.circular_progress)
- Slider (ui.slider)
- Switch (ui.switch)

### Affected components for [4]

All classes derived from the Element

### CODE REVIEW

**Comment by falkoschindler** [comment]
@FI-Mihej Thanks a lot for your contribution! I just started to have a look into it.

First of all: It seems to work! I can't reproduce any dropped keys and the UX is flawless for all elements from my comment https://github.com/zauberzeug/nicegui/issues/287#issuecomment-1405261469.

Some random thoughts:

- Regarding the "Affected components": Why are "ChoiceElements" `ui.radio`, `ui.toggle` and `ui.select` not affected?
- You introduced `**kwargs` for many elements. Is there a specific reason?
- The list of initializer parameters grew quite a bit. I'm still getting my head around the various new options, which of them are crucial for fixing #287, and which of them are "just" a nice addition.
- I'm also struggling to get the difference between `server_side_loopback` (true by default for value elements only) and `only_serverside_react` (same). Do we really need both (and expose them as public API)?

**Comment by falkoschindler** [comment]
I just noticed that binding between slider and progress elements is not working:

```py
lp = ui.linear_progress()
cp = ui.circular_progress()
ui.slider(min=0, max=1, step=0.1).bind_value_to(lp, 'value').bind_value_to(cp, 'value')
```

**Comment by FI-Mihej** [comment]
Hi @falkoschindler, thank you for your response!

1. "Regarding the "Affected components": Why are "ChoiceElements" ui.radio, ui.toggle and ui.select not affected?"
I just still need some additional time to correctly figure out their internals for a proper fix. May be it would be better to make an additional pull request later, since I have not a lot time for my own projects and for an open source activities, unfortunately (full time job, children).

2. "You introduced **kwargs for many elements. Is there a specific reason?"
No - it's just in case. Usually I prefer to give configurability to derived components when it is possible. For example, framework introduced Throttling but there were no way to configure it per component instance. Any way I'm not insisting - it's just a suggestion. I'll remove it if it conflicts with the development path of the framework.

3. "The list of initializer parameters grew quite a bit. I'm still getting my head around the various new options, which of them are crucial for fixing https://github.com/zauberzeug/nicegui/issues/287, and which of them are "just" a nice addition."
`server_side_loopback` and `throttle` can be removed from the component's initialization parameters list. However `server_side_loopback` should stay in `ValueElement's` initialization parameters list. `only_serverside_react` is better to leave in the component's initialization parameters list.

4. "I'm also struggling to get the difference between server_side_loopback (true by default for value elements only) and only_serverside_react (same). Do we really need both (and expose them as public API)?"
Before fix, items had next updating flow: user clicks a button -> an event sent to server -> server executes an `update()`, which -> sends an update packet back to the browser -> server executes `handlers()`, which -> sends an update packet back to the browser -> browser uses received update packets (from both `update()` and `handlers()`) one by one to actually update model (state) of the item -> browser actually and visually updates an item on the page. This is a Server Loopback (now it is can be turned on by `server_side_loopback=True`).
After fix, affected items (items with `server_side_loopback=False`) have next updating flow: user clicks a button -> js updates an item's model (state) immediately IF `only_serverside_react=False` -> an event sent to server -> server executes `handlers()`, which -> sends an update packet back to the browser -> browser uses received update packet to actually update model (state) of the item -> browser actually and visually updates an item on the page. This is a Browser Loopback. It doesn't call an `update()` on the server side (this is a crucial to eliminate issue) and can (by default) update item's model (state) immediately on the browser side (it is crucial for this fix as well since we need to actually and visually update state of the items anyway). As I said it has `only_serverside_react` configuration option. This option can be used in non-default state `only_serverside_react=True` when for example some Switch item must be actually (and visually) switched ON/OFF _only if and when server allowed to_ (by updating an item's state in `handler()` for example).
An algorithm of the Browser Loop can be seen in file `nicegui/templates/index.html`, in function `throttled_react_on_event` (previously it was named as `throttle` function).
A change for turning on/off an `update()` feature can be seen in file `nicegui/elements/mixins/value_element.py` - in both class constructor and in the `on_value_change` method.

5. "And what exactly is the purpose of the _update_tasks_queue? What is the problem with the original implementation?"
The problem is that an every call to `update()` actually register a new asynchronous task and all of them can be executed in a random order. As result an input ["s", "si", "sit", "site"] can lead to for example ["sit", "s", "site", "si"] packets send back to browser with a resulting "si" actual and visible to user state of the page item.

6. "I just noticed that binding between slider and progress elements is not working:"
Oh, I'll look to this issue as soon as I'll be able to. (As a fast fix, we may temporary exclude ui.slider from the list of an affected classes. If this issue is only for ui.slider of course)

If you will have an additional questions (of if my answers were not enough) - fell free to ask

**Comment by falkoschindler** [comment]
Thanks for the detailed explanation! There are quite some aspects involved.

Did you notice my comment https://github.com/zauberzeug/nicegui/issues/287#issuecomment-1407412181? After reading your PR I understood what I was missing and managed to come up with a rather minimalistic solution: https://github.com/zauberzeug/nicegui/tree/no_loopback_for_input. It basically represents your `server_side_loopback` and `only_serverside_react` with less changes to the existing implementation and API. Everything works as expected; we even test-deployed it to a preview server instance and verified that there are no dropped keys or alike.

Regarding the throttling API: We'd like to leave it out of the parameter lists for now, since there is no apparent reason to change it. And if so, one can use the more advanced `element.on` method. At least for this issue/PR a change is out of scope.

To get this issue resolved without you having to spend more time and work, let me propose the following procedure:

1. We would like to commit to your PR such that your changes get replaced with the content of the "no_loopback_for_input" branch and then merge into main. This might sound weird, but let me explain: We would prefer to keep changes to the code-base small. Changing too many aspects might be a bit risky and maybe not needed. But - and this is important to us - you would officially be listed as a contributor to NiceGUI, which is only fair, since "no_loopback_for_input" is based on your findings and your code.
2. Regarding the update task queue we will open a new issue. We think there is currently no urgent problem with mixing the order of UI updates. But there is indeed room for improvement: Firstly, we should _make sure_ that updates occur in the desired order. Secondly and maybe more importantly we could save unnecessary updates. E.g. when typing "abc" and we are sending state "a", state "ab" might get queued, but state "abc" can replace "ab" in the queue so that after "a" the next update contains "abc" directly. But these are thoughts for another issue.

Let us know if you have any remarks or concerns about the procedure and/or the implementation.

**Comment by rodja** [comment]
@FI-Mihej sorry to press the issue. We would really like to have this fix in the [v1.1.5 release](https://github.com/zauberzeug/nicegui/milestone/22) which is scheduled for today.

**Comment by FI-Mihej** [comment]
Hi @falkoschindle and @rodja,

First of all, sorry for a long response time: only today I've had an hour to read Github and to look to the code
And thank you: I really appreciate your procedure and have no concerns about the implementation
:)

**Pull request merged**
