### PR TITLE
UI.table from_pandas method

### PR DESCRIPTION
**Pull request by zilch42**
Adds `from_pandas` method to `ui.table` based on the similar method in `ui.aggrid`. 

Addresses #1972, including conversion of the non-serializable datatypes identified in #1698 

I think I have updated all of the documentation and tests but let me know if I have missed anything.

### CODE REVIEW

**Review by falkoschindler — APPROVED** [review]
Thanks a lot for this wonderful pull request, @zilch42!
Let's merge it right away 🚀

**Comment by rohitsathish** [comment]
@falkoschindler, as far as I can see, this problem still persists in 1.4.12. 
I get the following error when using ```ui.table.from_pandas()```:
```
Type is not JSON serializable: Timestamp
TypeError: Object of type Timestamp is not JSON serializable
```

**Comment by falkoschindler** [comment]
Thanks for reporting this reoccurring bug, @rohitsathish!
It seems to have re-appeared between 1.4.9 and 1.4.10. I'll create a new issue.

**Comment by falkoschindler** [comment]
@rohitsathish Can you share a minimal reproducible code example? The following code seems to be working:

```py
df = pd.DataFrame({'Name': ['John'], 'DOB': ['1/1/2000']})
df['DOB'] = pd.to_datetime(df['DOB'])
ui.table.from_pandas(df)
```

**Comment by rohitsathish** [comment]
@falkoschindler, looks like the time component is causing the error.

 ```python
  df = pd.DataFrame({'Name': ['John'], 'DOB': ['2021-06-25 03:00:00+00:00']})
  df['DOB'] = pd.to_datetime(df['DOB'])
  ui.table.from_pandas(df)
```

**Comment by falkoschindler** [comment]
@rohitsathish Looks like the timezone if causing the error. 🤦‍♂️
This works:
```py
df = pd.DataFrame({'Name': ['John'], 'DOB': ['2021-06-25 03:00:00']})
df['DOB'] = pd.to_datetime(df['DOB'])
ui.table.from_pandas(df)
```
I'll create a new issue.

**Pull request merged**
