### PR TITLE
Provide tests for run.io_bound and run.cpu_bound

### PR DESCRIPTION
**Pull request by rodja**
This PR adds tests for `run.io_bound` and `run.cpu_bound`. It also addresses an issue where the process pool could break.

### CODE REVIEW

**Comment by gotev** [comment]
@rodja can't see the details as they are expired. How can I help with this?

**Comment by rodja** [comment]
@gotev I'm not sure. Locally the tests seem to work, but as GitHub Action I still get errors. You should be able to see the failing tests now. Right?

**Comment by rodja** [comment]
There also was an issue in NiceGUI's `run.cpu_bound` where the process pool could break when an exception is raised which has a different set of parameters than its super class. I added a test to demonstrate/reproduce it.

**Review by falkoschindler — APPROVED** [review]
Ok. But I removed `loop.set_debug(False)` because `loop` has never been set and there is no running loop anymore.

**Pull request merged**
