### PR TITLE
fixed ui.download not working in native mode

### PR DESCRIPTION
**Pull request by Smug246**
Feature request: #2877

### CODE REVIEW

**Review by falkoschindler — COMMENTED** [review]
Thanks a lot for the pull request, @Smug246!

I just tested this simple test code on macOS:
```py
ui.button('Logo', on_click=lambda: ui.download(b'Hello World', 'hello.txt'))
```

Unfortunately I get this error:
```
--- Logging error ---
Traceback (most recent call last):
  File "/Users/falko/.pyenv/versions/3.11.7/lib/python3.11/logging/__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/Users/falko/.pyenv/versions/3.11.7/lib/python3.11/logging/__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/falko/.pyenv/versions/3.11.7/lib/python3.11/logging/__init__.py", line 687, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "/Users/falko/.pyenv/versions/3.11.7/lib/python3.11/logging/__init__.py", line 377, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
Call stack:
  File "/Users/falko/.pyenv/versions/3.11.7/lib/python3.11/site-packages/webview/platforms/cocoa.py", line 283, in download_completionHandler_error_
    logger.error('Download error:', error)
Message: 'Download error:'
Arguments: (Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL" UserInfo={NSLocalizedDescription=unsupported URL, NSErrorFailingURLStringKey=blob:http://127.0.0.1:1234/2c9d12b1-7c39-4d96-8294-1b8a5c8d5db0, NSErrorFailingURLKey=blob:http://127.0.0.1:1234/2c9d12b1-7c39-4d96-8294-1b8a5c8d5db0, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDownloadTask <7847E5B6-3828-4AD4-8FEE-E19F85617668>.<1>"
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalDownloadTask <7847E5B6-3828-4AD4-8FEE-E19F85617668>.<1>, NSUnderlyingError=0x12ca33bc0 {Error Domain=kCFErrorDomainCFNetwork Code=-1002 "(null)"}},)
```

Do you have an idea what's going on?

**Comment by Smug246** [comment]
ah it may be to do with macos. im on windows and dont have a mac to test

**Comment by Smug246** [comment]
uncapped_edit_1713025834898

**Comment by Smug246** [comment]
https://github.com/zauberzeug/nicegui/assets/99215486/f75d2ae3-cef2-4dca-ba5f-5e7971549f30

no problems for me with ur example

**Comment by Smug246** [comment]
Could you test this example and see if it works?
```python
import webview

if __name__ == '__main__':
    # Create a standard webview window
    webview.settings['ALLOW_DOWNLOADS'] = True
    window = webview.create_window('Simple browser', 'https://pywebview.flowrl.com/download')
    webview.start()
```

**Comment by falkoschindler** [comment]
Interesting:

- Your plain pywebview example works. And the "ALLOW_DOWNLOADS" flag matters.
- A NiceGUI test with the same URL works, independent of the "ALLOW_DOWNLOADS" flag:
    ```py
    ui.button('Logo', on_click=lambda: ui.download('https://pywebview.flowrl.com/download/test-data.bin'))
    ```

Anyway, enabling this flag seems to help in some cases. But I wonder if we really should enable it by default, since pywebview probably disabled it for a reason. And technically it would be a breaking change.

We could easily make it configurable though: Adding `settings` to `NativeConfig`
```py
@dataclass(**KWONLY_SLOTS)
class NativeConfig:
    start_args: Dict[str, Any] = field(default_factory=dict)
    window_args: Dict[str, Any] = field(default_factory=dict)
    settings: Dict[str, Any] = field(default_factory=dict)
    main_window: Optional[WindowProxy] = None
```
and using them
```py
    webview.settings.update(**core.app.native.settings)
```
before creating the `window`. We could even print a warning if the user calls `ui.download` in native mode without having this flag enabled.

**Comment by Smug246** [comment]
so although that error occurs on mac you still think it should be default setting. i feel like that would cause numerous issues.

**Comment by falkoschindler** [comment]
Let me clarify: I think we should make `webview.settings` configurable with `ALLOW_DOWNLOADS` being false by default. This way we don't introduce breaking changes and give full control to the user.

**Comment by Smug246** [comment]
oh right i misunderstood. i'll take my best shot at it

**Comment by Smug246** [comment]
should i make it configurable through ui.run() parameters?

**Comment by falkoschindler** [comment]
As mentioned [above](https://github.com/zauberzeug/nicegui/pull/2884#issuecomment-2053978745), I think we should add  `settings` to `NativeConfig`. Then the user can configure it via
```py
app.native.settings['ALLOW_DOWNLOADS'] = True
```
like it's already possible for `app.native.window_args` and `app.native.start_args`:
https://nicegui.io/documentation/section_configuration_deployment#native_mode

**Comment by Smug246** [comment]
what do you think?

**Comment by Smug246** [comment]
had to make a quick revision because i confused myself lol

**Review by falkoschindler — APPROVED** [review]
Thanks, @Smug246!
Looks good to me. 😎

**Pull request merged**
