### PR TITLE
Carousel component

### PR DESCRIPTION
**Pull request by michangelis**
In this PL i added a directory in examples page featuring a simple carousel component. I also modified the tests.yml file to pass by handling the case where the Slack webhook secret is not defined

### CODE REVIEW

**Comment by rodja** [comment]
I like this example much better than #1091 because it is [focused on a single thing](https://github.com/zauberzeug/nicegui/blob/main/CONTRIBUTING.md#examples) instead of introducing complexity with sqlite etc.
But maybe the example could even be improved by also introducing a new element `ui.carousel` which should be based on https://quasar.dev/vue-components/carousel...

**Comment by falkoschindler** [comment]
Thanks for this PR, @michangelis! Extending our collection of examples is always a good idea.

In this case, however, I have some concerns. The example basically boils down to this:

```py
images = [
    'https://picsum.photos/id/30/640/360',
    'https://picsum.photos/id/31/640/360',
    'https://picsum.photos/id/32/640/360',
]

with ui.tab_panels(ui.tabs(), value=0) as panels:
    for index, url in enumerate(images):
        with ui.tab_panel(index):
            with ui.card().classes('w-96 items-center'):
                ui.label(f'Image {index+1}')
                ui.image(url)
                ui.button(on_click=lambda: panels.set_value((panels.value - 1) % len(images)), icon='arrow_back') \
                    .props('fab-mini').classes('absolute top-1/2 left-2')
                ui.button(on_click=lambda: panels.set_value((panels.value + 1) % len(images)), icon='arrow_forward') \
                    .props('fab-mini').classes('absolute top-1/2 right-2')
```

You're using tabs and tab panels to recreate a carousel view. It feels a bit weird, e.g. because the buttons are placed within each tab, causing them to move when switching tabs.

Quasar has a UI component [QCarousel](https://quasar.dev/vue-components/carousel). We should try creating an example using this component rather than creating one ourselves. And if that works well, we can turn it into a new UI element.

**Comment by falkoschindler** [comment]
This is basically the same example using QCarousel:

```py
images = [
    'https://picsum.photos/id/30/640/360',
    'https://picsum.photos/id/31/640/360',
    'https://picsum.photos/id/32/640/360',
]

with ui.element('q-carousel').props('model-value=0 animated arrows') as carousel:
    for index, url in enumerate(images):
        with ui.element('q-carousel-slide').props(f'name={index}'):
            ui.image(url).classes('w-[640px]')
carousel.on('update:model-value', lambda e: carousel.props(f'model-value={e.args}'))
```

Especially the last line is a bit awkward. But once this is wrapped into a dedicated ValueElement, it's no longer needed.

**Comment by falkoschindler** [comment]
Ok, I'd like to close this PR in favor of #1176. But in order to acknowledge the idea for a carousel element and the effort you put into #1087 and #1091, I did an empty merge of this PR into #1176. This makes you an official contributor to NiceGUI. 🙂

**Comment by michangelis** [comment]
@falkoschindler thank you so much for your consideration and i wanted to open a new PL with the Quasar carousel implemented but between my school exams and work i have been swamped. As a thanks to your acknowledgement and in order to me to earn properly the title of contributor i would like to be assigned this task if it not already implemented

**Pull request merged**
