### PR TITLE
Introduction of Standalone-Mode (eg. Desktop Window)

### PR DESCRIPTION
**Pull request by rodja**
This PR is based on the discussions in #89 and introduces two new flags for `ui.run`. 

"standalone" opens a desktop window and seeks automatically for an open port, so users do not need to bother with another app blocking the startup.

"fullscreen" activates "standalone" but directly opens the app in fullscreen mode.

### CODE REVIEW

**Review by falkoschindler — COMMENTED** [review]
@rodja I went through the code and cleaned up a little here and there. I think I could straighten the function signatures a bit, but maybe this is a matter of taste.

But one major thing: `uvicorn.Config` and `open_window` still used the default port 8080, since you only set `globals.port` to the automatically detected port. But `globals.port` is only used for the print statement "NiceGUI ready to go on...". I fixed it to update the `port` argument right at the beginning of `ui.run` and to pass it down to `open_window`.

But there is still one issue: Do we really need the automatic port detection? The problem is that it runs every time `ui.run` is called. But when auto-reloading, a _new_ unused port is searched. This is why the print statement always shows a different port than the one which is actually used.

**Comment by rodja** [comment]
Ok, thanks for the review. I think the auto-port discovering is quite crucial. Not specifically for development but if the app is packaged with PyInstaller. When running standalone, the user does not care about the port and that there is a server in the background.

But I could not find a simple solution. So we should do it on a different pull-request.

**Comment by falkoschindler** [comment]
I see. It would be really handy to get the port automatically.
Did you know you can start uvicorn with port=0 to get a "random" port? So we don't need to re-implement this part.
It only remains unclear how to get the port from within the restarted subprocess.

**Comment by ItsCubeTime** [comment]
> I see. It would be really handy to get the port automatically. Did you know you can start uvicorn with port=0 to get a "random" port? So we don't need to re-implement this part. It only remains unclear how to get the port from within the restarted subprocess.

Im curious to see how you solve this, one idea would be to write the port to the OS file system using Pythons "Fifo pipes" and read that on the main process.

If youre not familiar, heres a generic fifo pipe example:
 https://gist.github.com/komuw/52f796677b88773f9b3d573526f44809

**Comment by rodja** [comment]
@ItsCubeTime thanks for the reference. I was not aware of the fifo pipe. Unfortunately the os.mkfifo function is not available on Windows, as it is a Unix-specific feature. The current implementation already uses multiprocessing.event. Maybe it need to be upgraded to [multiprocessing.Pipe](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.Pipe). That would also pave the way for later features like programatically changing the window-size, fullscreen-mode etc.

**Comment by rodja** [comment]
> Did you know you can start uvicorn with port=0 to get a "random" port? So we don't need to re-implement this part.

Yes, but ChatGPT says that it will only provide an available port. Not necessarily a working one. For example there could be firewall rules in place which hinder opening the port.

**Pull request merged**
