### PR TITLE
Introduce from_pyecharts method for ui.echart 

### PR DESCRIPTION
**Pull request by CrystalWindSnake**
This PR introduces ui.echart.from_pyecharts() to create a echart from [pyecharts](https://github.com/pyecharts/pyecharts/blob/master/README.en.md)
The functions are as follows:
1. Build from pyecharts chart object
2. Automatic conversion of js code defined in pyecharts.

sample code:
```python
from pyecharts import options as opts
from pyecharts.charts import Bar
from pyecharts.commons import utils

from nicegui import ui

bar = (
    Bar()
    .add_xaxis(["Mon","Tue","Wed","Thu","Fri","Sat","Sun"])
    .add_yaxis("series A",[120, 200, 150, 80, 70, 110, 130],)
    .set_global_opts(
        xaxis_opts=opts.AxisOpts(
            axislabel_opts={
                # Setting up js functions the nicegui way
                ":formatter":
                    """function (value, index) {
    return 'x for ' +  value ;
}"""
            }
        ),
        yaxis_opts=opts.AxisOpts(
            axislabel_opts={
                # Setting up js functions the pyecharts way
                "formatter": utils.JsCode(
                    """
function (value, index) {
    return value + 'kg';
}"""
                )
            }
        )
    )
)

ui.echart.from_pyecharts(bar)

ui.run()
```

### CODE REVIEW

**Review by falkoschindler — CHANGES_REQUESTED** [review]
Hi @CrystalWindSnake, thanks for the pull request!

I just updated the code with some minor changes:
- added more type annotation,
- improved docstrings, and
- switched from static to class methods.

My main concern is the new simplejson dependency. Can we get along without adding this particular JSON library?

Besides that, we should
- [ ] improve the way we use the optional pyecharts dependency (see pandas in aggrid.py for a pattern we like to use throughout the codebase),
- [ ] add some simple pytest, and
- [ ] add a demo to the documentation.

By the way, I experimented with this simplified demo code:
```py
from pyecharts import options
from pyecharts.charts import Bar
from pyecharts.commons import utils
from nicegui import ui

ui.echart.from_pyecharts(
    Bar()
    .add_xaxis(['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'])
    .add_yaxis('series A', [120, 200, 150, 80, 70, 110, 130],)
    .set_global_opts(
        xaxis_opts=options.AxisOpts(axislabel_opts={':formatter': r'(val, idx) => `x for ${val}`'}),
        yaxis_opts=options.AxisOpts(axislabel_opts={'formatter': utils.JsCode(r'(val, idx) => `${val} kg`')}),
    )
)
```

**Comment by CrystalWindSnake** [comment]
I haven't delved into the details of pyecharts for serialization. But pyecharts relies on simplejson, and using pyecharts should come with simplejson installed.

**Comment by falkoschindler** [comment]
Ah, I see! That simplifies things.
Meanwhile I refactored the code once again and fixed the import of the optional pyecharts module.

**Comment by CrystalWindSnake** [comment]
@falkoschindler Thanks for the help, I'll take the time to add some unit tests

**Pull request merged**
