### PR TITLE
Register plotly event handlers only once, at mount

### LINKED ISSUE #2504: multiplying events
### Description

1. I want to listen for a click event on one plotly plot, then use that to update a second plotly plot.
2. I expect the `on('plotly_click', ...)` handler to fire exactly once for each click
3. Instead, the handler fires 3x on the first click, then 4x on the second click, then 5x ... etc.

Here is code to reproduce the issue:
```python
from nicegui import ui
import plotly.graph_objects as go

fig = go.Figure(go.Scatter(x=[0,1,2,3,4], y=[3,5,2,7,8]))
plot = ui.plotly(fig)

fig2 = go.Figure(go.Scatter(x=[0,1,2,3,4], y=[2,5,1,2,1]))
plot2 = ui.plotly(fig2)

def click_handler(ev):
    plot2.update()
    print(ev.args)

plot.on("plotly_click", click_handler)
ui.run()
```

### PR DESCRIPTION
**Pull request by bmaranville**
All the event handlers in plotly were being registered on every update, which was causing a lot of issues.  Event handlers should only be registered once.  This PR moves the registration of the event handlers to a one-time operation in the `mounted()` function.

Fixes #2504, I think

### CODE REVIEW

**Comment by platinops** [comment]
I think this also fixes #2435.

**Comment by bmaranville** [comment]
This may not be quite right... it looks like when calling `Plotly.newPlot()` the listeners are dropped.  A simply fix might be to move the `set_handlers()` function call from `mounted()` to right after `Plotly.newPlot()`, inside the `update` method.  I'm trying that out right now.

**Review by falkoschindler — APPROVED** [review]
Thanks for this pull request, @bmaranville!

I looks like it fixes a really st*pid mistake. 😄 Of course, we shouldn't re-assign event handlers on every update!

But why do you think there's something wrong? Do you have an example? It tested with the following code and it seems to work nicely:
```py
fig = go.Figure()
plot = ui.plotly(fig).classes('w-full h-96').on('plotly_click', ui.notify)

def add_trace():
    fig.add_trace(go.Scatter(x=[1, 2, 3], y=[random(), random(), random()]))
    plot.update()

ui.button('Add trace', on_click=add_trace)
```

**Comment by bmaranville** [comment]
What I forgot is that changing the config causes newPlot to be triggered on `update()`, after which the events are no longer firing.  I actually ran in to this during testing of my app and was confused again.
So moving `this.set_handlers();` right after `Plotly.newPlot(...)` seems to do the right thing - it registers the event listeners once per `newPlot` (lifetime of the plot) instead of once per lifetime of the component.

**Comment by falkoschindler** [comment]
Well, I still can't reproduce `newPlot` dropping event registrations (see my above-mentioned test code).

But I can confirm that toggling the visibility stops events from firing. 😕

**Comment by bmaranville** [comment]
I don't think your code above triggers another newPlot after the first one - I think the only way to do that is to use the `dict` form of figure and then alter `fig['config']` between plot updates. (the guard logic around newPlot only passes if the config changes, not from adding traces or changing layout.)  Here is code that reproduces the problem:

```python

from nicegui import ui
from numpy.random import random
import plotly.graph_objects as go

fig = { "data": [], "config": {} }
plot = ui.plotly(fig).classes('w-full h-96').on('plotly_click', ui.notify)

def add_trace():
    fig['data'].append(go.Scatter(x=[1, 2, 3], y=[random(), random(), random()]).to_plotly_json())
    plot.update()

def add_drawrect():
    fig['config']['modeBarButtonsToAdd'] = ['drawrect']
    plot.update()

ui.button('Add trace', on_click=add_trace)
ui.button('Enable scroll Zoom', on_click=add_drawrect)

ui.run()
```

**Comment by falkoschindler** [comment]
Oh right, thanks! That makes sense.
I think we should merge this fix, even though there's still a problem with toggling the visibility. That's probably a separate issue and hasn't been introduced with this PR.

**Pull request merged**
