### PR TITLE
add fullcalendar_more_options

### PR DESCRIPTION
**Pull request by dorel14**
Add fullcalendar_more_options example in order to what can be made with Fullcaendar with differents options activated 

More: 

you will have an example of handling date and event click + a form to add events 

---

Feature request: #3516

### CODE REVIEW

**Comment by rodja** [comment]
Thanks for your efforts @dorel14! Looks really promising and we are glad you found a way. Bit it's way to much files and external code for a simple example. Maybe you can create it as a seaprate GitHub project and we link it in the README.md of the example?

**Comment by dorel14** [comment]
Here thé LinkedIn to thé example in my repo 

https://github.com/dorel14/nicegui/tree/main/examples/fullcalendar_more_options

**Comment by rodja** [comment]
Yea. Maybe you can extract it into an own repo? That way the code can stand for itself and not be part of a fork...

**Comment by dorel14** [comment]
Here it is 

[https://github.com/dorel14/NiceGui-FullCalendar_more_Options](https://github.com/dorel14/NiceGui-FullCalendar_more_Options)

**Comment by rodja** [comment]
Thanks @dorel14. I added the link in PR #3553.

**Pull request closed without merging**
