### PR TITLE
Auto update page before each await in a generator-style page

### PR DESCRIPTION
**Pull request by rodja**

### CODE REVIEW

**Comment by rodja** [comment]
The original issue from #142 with the dialog is still not working. And many other things. But I got the following to run as expected:

```python
@ui.page('/')
async def page() -> Generator[None, PageEvent, None]:
    ui.label('before page is ready')
    yield
    ui.label('page ready')
    await asyncio.sleep(1)
    ui.label('one')
    await asyncio.sleep(1)
    ui.label('two')
    await asyncio.sleep(1)
    ui.label('three')
```

**Comment by falkoschindler** [comment]
Great idea! Review looks good, tests are green.
We can treat more coros with the new `update_after_await` wrapper and think about the name (Isn't it an "update *before* await"?). But we can also merge onto main and improve on it later.

**Comment by falkoschindler** [comment]
The test_autoupdate_on_async_timer_callback was failing. So I replaced it with the one I already implemented in test_timer.py, which works better on GitHub.

**Review by falkoschindler — COMMENTED** [review]
Ok

**Pull request merged**
