### PR TITLE
ui.number value discrepancy

### PR DESCRIPTION
**Pull request by frankvp11**
This is the fix as described in #3142

### CODE REVIEW

**Review by falkoschindler — CHANGES_REQUESTED** [review]
Thanks for the pull request, @frankvp11!

However, this will result in an event value `None` when entering "0". 🤔

**Comment by frankvp11** [comment]
Huh, I didn't see that coming... 
Because you've said that I've thought about the other possible cases where this can happen, and I believe that this would be the only one.
I think that doing something like this would fix it. Do you agree?
```python
def _value_to_event_value(value: Any) -> Any:
    if value == 0:
        return 0
    if value:
        return float(value)
    return None
```
This covers both cases where the value is 0 or 0.0. The other cases where the previous code could have failed is from some empty collection (list, dict, set, etc). I don't think we should worry about those though and can safely return None in those cases.

**Comment by falkoschindler** [comment]
Yeah, the devil is in the details...

I think we can simplify your solution:
- if value is 0: return `0` (equal to `float(value)`)
- if value is truthy (i.e. not `None`): return `float(value)`
- else: return `None` (which should be `value`)

So basically we are converting to a float whenever `value` is not None:
```py
return float(value) if value is not None else value
```

But now that I think of it, what's the purpose of this conversion anyway? `value` should be of type `float | None` already. Should we simply remove this override of `_value_to_event_value` and use its base implementation, which simply returns `value`? It seems like its sole purpose was to convert `None` to 0.

**Comment by frankvp11** [comment]
That's what it looks like. As for your implementation, it does indeed look simpler, I can change mine to that if you'd like?

**Pull request merged**
