### PR TITLE
allow creating ui.aggrid from pandas dataframe

### PR DESCRIPTION
**Pull request by falkoschindler**
This PR introduces `ui.aggrid.from_pandas()` to create a new AG Grid from a Pandas DataFrame.
The idea came up in discussion https://github.com/zauberzeug/nicegui/discussions/388.

I'm just a bit unsure about the type annotation: I annotated `df` with the string `'pandas.DataFrame'` to avoid a package dependency to pandas. But now VSCode thinks `df` would be of type Any. I tried to improve the annotation without importing pandas, but without success. Maybe we just leave it like this.

### CODE REVIEW

**Comment by Shahin-rmz** [comment]
Nice PR.
BTW, as of now, there are two other libs other than pandas, that have different kind of `df` s than traditional `pandas.DataFrame`.
They are [Polars](https://www.pola.rs/) *Dataframe written in Rust with Python API* and also [pandas2](https://pandas.pydata.org/pandas-docs/version/2.0/getting_started/install.html).
I think they have good potential for future. also `Polars` didn't work too well with the code that I have written (maybe it's the `polars` problem.

**Comment by Shahin-rmz** [comment]
[This](https://pynecone.io/docs/library/datadisplay/datatable) also I found very useful.
Just to the point.
If you like to consider.

**Comment by falkoschindler** [comment]
> there are two other libs other than pandas, that have different kind of dfs

That's why I chose the name `from_pandas`. In the future we can easily add `from_polars` and `from_pandas2`.

> [This](https://pynecone.io/docs/library/datadisplay/datatable) also I found very useful.

Do you mean the API?
Yes, parameters like `columns`, `search`, `sort`, `resizable`, and `pagination` would be a nice addition.

**Comment by Shahin-rmz** [comment]
> Yes, parameters like `columns`, `search`, `sort`, `resizable`, and `pagination` would be a nice addition.


Yes I meant parameters, specially search one.
I had some problems searching for the rows which are not inside DOM,
not sure what was the problem.

Here is an example of what I search on top of the page.
image


the same search on bottom of the page
image

Can not understnatd it!

**Comment by falkoschindler** [comment]
@dclause These are very good questions.

1. I'm starting to think the same. Originally, when NiceGUI built upon JustPy, we somehow _had_ to support it. And I assumed it to be such a web standard that NiceGUI should have it. But I'm starting to like QTable more and more, and putting work into two table implementations seems a bit inefficient. Maybe this is something for a separate discussion about AG Grid's future in NiceGUI.

2. I think it would be _nice_ to provide easy-to-use interfaces from common data frameworks to NiceGUI's table element. Being able to simply plug some data into `ui.table` in one line of code is very valuable for quickly prototyping a small UI to present some data, independent of a more powerful and more flexible API that's also available.

**Pull request merged**
