### PR TITLE
Added point dragging to chart element.

### PR DESCRIPTION
**Pull request by natankeddem**
I have extended the current chart element to include a new feature. Point dragging allows live manipulation of the chart element. I have included an on_change callback to allow the monitoring of chart changes on the backend.

### CODE REVIEW

**Review by falkoschindler — CHANGES_REQUESTED** [review]
Thanks a lot for this PR, @natankeddem! I have some remarks though:

1. First of all: The user experience is pretty poor. Maybe it's just my machine, but while dragging the tooltip flickers back and forth between different points. This seems like a pure Highcharts problem. But how can we improve on that?
2. I find the parameter name `on_change` a bit vague. If we add more events in the future, we might run into naming conflicts. I think `on_point_drop` fits more precisely.
3. We should introduce more specific event arguments, like the `SceneDragEventArguments` I just implemented for PR #1201.
4. The example isn't too long. Therefore I think we can move it into chart_documentation.py.
5. Instead of implicitly registering for drag events by specifying `plotOptions.series.dragDrop`, I would check if the `on_point_drop` handler is set and somehow pass the information to the frontend using a dedicated prop.

**Comment by natankeddem** [comment]
> Thanks a lot for this PR, @natankeddem! I have some remarks though:
> 
> 1. First of all: The user experience is pretty poor. Maybe it's just my machine, but while dragging the tooltip flickers back and forth between different points. This seems like a pure Highcharts problem. But how can we improve on that?
* It looks like I was missing some options that make dragging work more cleanly. Does this work any better for you now?
> 2. I find the parameter name `on_change` a bit vague. If we add more events in the future, we might run into naming conflicts. I think `on_point_drop` fits more precisely.
* done
> 3. We should introduce more specific event arguments, like the `SceneDragEventArguments` I just implemented for PR [Support drag and drop for 3D objects in `ui.scene` #1201](https://github.com/zauberzeug/nicegui/pull/1201).
* I will investigate this further.
> 4. The example isn't too long. Therefore I think we can move it into chart_documentation.py.
* done
> 5. Instead of implicitly registering for drag events by specifying `plotOptions.series.dragDrop`, I would check if the `on_point_drop` handler is set and somehow pass the information to the frontend using a dedicated prop.
* Still working on this, I can't seem to get `self._props` to propagate the value to the javascript for some reason. I'll keep working on this.

**Comment by natankeddem** [comment]
I am hoping this is somewhere close to what you are expecting for the events? I had a hard time deciding how to organize the events and the number of callbacks. By the end I thought it seemed logical to group the callbacks into `on_events` and `on_drag_drop`. There are a few more events that Highcharts can fire but I figured we can add them later on if people end up needing them. There might be some special context those events might need to return for those use cases so we will have a better idea how to implement them at that point.
I still can't seem to pass the self._props to the front end js so for now I just made that injection logic true. If you see anything obvious let me know, I am guessing I am doing something stupid here but I just can't understand why it isn't working.

**Comment by natankeddem** [comment]
I tried changing the event handlers into privates (add _ before methods) but that seemed to break whatever magic you guys have behind the curtain with the event args.

**Comment by falkoschindler** [comment]
@natankeddem Thanks a lot for the update! 🙂

I just spent some time with the code and changed it yet again:

- A was a bit confused by the event arguments. It seemed a bit inconsistent. But I have to commit: The original Highcharts events aren't very consistent either. Sometimes there's a `point` argument, sometimes it's called `target`. And why are there almost no arguments for "dragStart"? Strange.
  I decided to stay close to the original arguments. But since we can't transfer points anyway due to their cyclic structure, I kept `point_index`, `point_x` and so on for all events involving a point. But I removed the series name etc. because is seemed a bit arbitrary. With the series index it should be easy for the user to get further information about the series.

- And I noticed that we don't need another mechanism for registering certain event types. The client can simply emit all events and NiceGUI's event system will automatically transmit only event that have an event listener registered with `.on(...)`. This system also takes care of filtering the arguments to reduce the payload.
  It only catch is that we can't simply emit points or series but have to preprocess them with the new `uncycle` function.

What do you think? Do you have any objections or should we merge into main?

**Review by falkoschindler — APPROVED** [review]

**Comment by natankeddem** [comment]
Thank you for working this through with me @falkoschindler. There are many ways to make this work but I was really unsure of the "best" path at times and iterated through quite a few different event/callback/argument configurations.

I had a similar discrete  event organization in one of my internal iterations. The only reason I switched was because I wasn't sure it was acceptable to have so many callback arguments with the possibility of more in the future. Since there are some untapped events in highchart that aren't point specific which we are not exposing here yet.

I can also understand the argument to minimize the series information returned. Since the user should still have the original data to rebuild the series with the new point coordinates. It was more a quality of life option to include it but I can see how passing large sets of data or otherwise including it would be an issue. Best to keep with the minimum required as you have done.

I am good with the changes as is.

I also made up a demo/edge case test just to see if I could break anything with these new additions. I found no issues.

```
from random import random

from nicegui import ui

options = {
    'title': False,
    'plotOptions': {
        'series': {
            'stickyTracking': False,
            'dragDrop': {'draggableY': True, 'dragPrecisionY': 1},
        },
    },
    'series': [
        {'name': 'A', 'data': [[20, 10], [30, 20], [40, 30]]},
        {'name': 'B', 'data': [[50, 40], [60, 50], [70, 60]]},
    ],
}


def on_point_drop(e):
    chart.options['series'][e.series_index]['data'][e.point_index] = [e.point_x, e.point_y]


chart = ui.chart(
    options,
    extras=['draggable-points'],
    on_point_click=lambda e: ui.notify(f'Click: {e}'),
    on_point_drag_start=lambda e: ui.notify(f'Drag start: {e}'),
    on_point_drop=lambda e: on_point_drop(e)
).classes('w-full h-64')


def change_point():
    chart.options['series'][0]['data'][0] = random()*20
    chart.update()


ui.button('Change Series 0', on_click=change_point)


def add_point():
    last_x = chart.options['series'][0]['data'][-1][0]
    chart.options['series'][0]['data'].append([last_x+10, random()*20])
    chart.update()


ui.button('Add Point to Series 0', on_click=add_point)


def remove_point():
    del chart.options['series'][0]['data'][-1]
    chart.update()


ui.button('Remove Point in Series 0', on_click=remove_point)


def add_series():
    last_x = chart.options['series'][0]['data'][-1][0]
    chart.options['series'][0]['data'].append([last_x+10, random()*20])
    chart.update()
    chart.options['series'].append({
        'data': [[int(random() * 20), int(random() * 20)],
                 [int(random() * 20), int(random() * 20)],
                 [int(random() * 20), int(random() * 20)]]})


ui.button('Add Series', on_click=add_series)


def remove_series():
    del chart.options['series'][-1]
    chart.update()


ui.button('Remove Series', on_click=remove_series)
ui.run()

```

**Pull request merged**
