### PR TITLE
Adding autocomplete as a public persisted property

### PR DESCRIPTION
**Pull request by jasonmcculloch3**
Effectively I am proposing that the autocomplete list can be either:
- **Lazily loaded** i.e. starts off None and then later on can be populated via the `autocomplete` property
- **Dynamically updated** i.e. can be dynamically changed based on external factors

In my situation I want to delay the reading of data from the database until the user specifically goes into that area so that my application is snappy and fast.

If there is another way to do this then I would be interested to know your thoughts.

### CODE REVIEW

**Comment by rodja** [comment]
Nice! What do you think @phoskee and @falkoschindler? Could you make reviews?

**Comment by jasonmcculloch3** [comment]
Hey @rodja I am also trying to build in some tests, so will commit once done. Awesome project BTW!

**Comment by jasonmcculloch3** [comment]
@rodja / @falkoschindler I have resolved the conflict in the unit tests.

**Comment by falkoschindler** [comment]
Thanks, @WolfgangFahl, I'll look into it.
The whole autocompletion topic is kind of on hold because we're planning to implement it on the client. Therefore we need a wrapper component for QInput, which I haven't had time for yet. But it would allow us to trigger the right behavior depending on the platform, either desktop or mobile. And it will reduce the latency quite a bit if we don't need to send input value and completion options back and forth between client and server. Anyway, a package like autocompleter might come in handy.

**Comment by falkoschindler** [comment]
Thanks, @jasonmcculloch3, for your effort and thought you've put into this pull request. It added to our ongoing discussion around the autocomplete functionality.

Upon deeper exploration, we found that server-side implementation was proving a tad slow and lacking the flexibility we needed for device-specific UX features, like datalists on mobile devices. As a result, we've shifted the implementation to the client-side (you can see the changes here: https://github.com/zauberzeug/nicegui/pull/1063).

This move introduced a new `set_autocomplete` method, which can directly update the `autocomplete` list. While this does mean that your PR might not be needed in its current form, I'd like to point out the meaningful role your work played in advancing the conversation to this point.

Thank you again for your valuable input, and we look forward to your future contributions.

**Pull request closed without merging**
