### PR TITLE
integer argument for ui.number

### PR DESCRIPTION
**Pull request by groucho86**
Feature to allow for an integer to be the returned type of ui.number instead of the default float. Example provided as well.

Feature request: #1921

### CODE REVIEW

**Comment by falkoschindler** [comment]
Thanks for this pull request, @groucho86!

While reviewing the code and writing a test for the new feature, I came up with two questions:

1. You added
    ```py
    if self.value is None and 'clearable' in self._props:
        self.set_value(None)
    else:
        ...
    ```
    As far as I can tell, this changes the behavior for non-integer number elements too. Is there a specific reason why you need this check and cannot rely on the line `value = float(self.value or 0)` which handles `None`?

2. I wanted to test
```py
    number.set_value(1.23)
    screen.should_contain("value: 1, type: <class 'int'>")

    number.value = 4.56
    screen.should_contain("value: 4, type: <class 'int'>")
```

**Comment by falkoschindler** [comment]
Thanks for this pull request, @groucho86!

While reviewing the code and writing a test for the new feature, I came up with two questions:

1. You added
    ```py
    if self.value is None and 'clearable' in self._props:
        self.set_value(None)
    else:
        ...
    ```
    As far as I can tell, this changes the behavior for non-integer number elements too. Is there a specific reason why you need this check and cannot rely on the line `value = float(self.value or 0)` which handles `None`?

2. I wanted to test
    ```py
    number.set_value(1.23)
    screen.should_contain("value: 1, type: <class 'int'>")

    number.value = 4.56
    screen.should_contain("value: 4, type: <class 'int'>")
    ```
    But currently the assigned value isn't converted into integers. What do you think: Should the value _always_ be converted to `int` or only after user input?

Note that I already have commits with a potential refactoring and the new pytest, but I wanted to clarify these conceptual aspects first before pushing them to your branch.

**Comment by groucho86** [comment]
Hi Falko,
Thank you for your diligence!

1. This bit of code seemed to solve [this bug report](https://github.com/zauberzeug/nicegui/issues/1765)
2. I would be happy for the number to always be integer. I went with the easier route of "sanitize on blur" but if you can see how to force integer/float from the get-go, that would be great.

**Comment by falkoschindler** [comment]
> 1. This bit of code seemed to solve [this bug report](https://github.com/zauberzeug/nicegui/issues/1765)

Ah, I see. 👍🏻

> 2. I would be happy for the number to always be integer. I went with the easier route of "sanitize on blur" but if you can see how to force integer/float from the get-go, that would be great.

Yes, I agree. A number element that always holds an integer would feel very consistent. But this could lead to the following problem:
Assume a `ui.number` being bound to a slider with step size 0.1. Moving the slider will cause a mismatch between both values, so the number is updated. But if we run a sanitization (at least applying the floor function), the binding loop will still find a mismatch in the next iteration and will constantly try to update the number.

In a discussion with @rodja we noticed the similarity between flooring to an integer and applying min/max limits. Maybe we should view the "integer" mode as a part of the sanitization. Like min/max we shouldn't enforce the integer value when setting the value programmatically (or via binding), but only to sanitize user input. This would leave the implementation unchanged and the pytest shouldn't expect an int value after using `set_value`. 👍🏻

Another question: Is there a specific reason you use `floor()`? I could imagine to use `round()` instead. Or in the spirit of the other sanitization parameters `min` and `max`: We could introduce a parameter `digits` (instead of `integer`) which rounds to the given number of digits. This would give more flexibility and is maybe even more intuitive. What do you think, @groucho86?

**Comment by groucho86** [comment]
Indirectly answering your first question with another question... could we somehow reject the typing or pasting or binding of anything that contains "." if self.integer is True?

> We could introduce a parameter digits (instead of integer) which rounds to the given number of digits.
That is quite elegant, but my need is for ui.number to specifically return an integer, not for a no-decimal float.

I think I went with floor for the "simplicity" of it. Happy to have it switched to round!

**Comment by falkoschindler** [comment]
I just implemented the new `digits` parameter. The code turns out pretty nice and simple. I just wonder if "precision" would be a better name instead of "digits". The latter could also be understood as, e.g., the number of digits in a phone number.

**Comment by groucho86** [comment]
I like it! Very clean.

**Comment by rodja** [comment]
Yes, it looks great. But I would also prefer `precision` over the parameter name `digits`.

**Review by falkoschindler — APPROVED** [review]
Alright, I think this PR is ready to merge! 🎉

**Review by rodja — COMMENTED** [review]
Looks great!

**Pull request merged**
