### PR TITLE
Allow passing local file path to ui.download

### PR DESCRIPTION
**Pull request by rodja**
This PR enhances the `ui.download` element to also work with local file paths (like `ui.image` etc)

### CODE REVIEW

**Review by falkoschindler — COMMENTED** [review]
I reviewed the PR:

- For consistency I chose to use `helpers.is_file` for checking if `src` is a local file.
- I moved the definition of `DOWNLOAD_DIR` out of test_helpers.py, because this file isn't meant to be a place for "test helpers", but rather a file testing the helpers.py file.
- I don't approve the PR, yet, because there is a potential memory leak: For every download there is a new route added to the FastAPI app. Now there are two cases:
    1. There are different file, e.g. captured images. Every download of the current image creates a new route which is never cleaned up, even if the image is eventually removed from memory.
    2. There is some button like a "Download the datasheet of our great product" triggering the download of a local PDF. Each client clicking the button will create another route with the same path. For a well visited website this might eventually be a significant leak.
    So I wonder if there's an alternative to avoid accumulating routes.

**Comment by rodja** [comment]
You are right. `ui.download` is not a normal element. We need to think a bit more about how we approach this.

**Comment by rodja** [comment]
Maybe we can create a unique route if the download is executed and remove it after the file has been served. Kind of a one-time-download-route. We do something similar in https://github.com/zauberzeug/nicegui/blob/main/examples/download_text_as_file/main.py.

**Comment by falkoschindler** [comment]
@rodja I implemented such single-use download routes. Have a look. 🙂

**Comment by rodja** [comment]
Super cool :-)

**Pull request merged**
