### PR TITLE
Adjusting validation element for better err_msg

### PR DESCRIPTION
**Pull request by steweg**
This patch adjust validation element to allow user to specify validation function that dynamically returns error message

---

[Note by the maintainer] Related to feature request #2150.

### CODE REVIEW

**Comment by falkoschindler** [comment]
Thanks for the pull request, @steweg!
Can you elaborate on which problem you're trying to solve? How would I use the new feature? Is it related to #2150?

**Comment by steweg** [comment]
Hi,

It is not related to #2150. I am currently working on project which uses nicegui to create dynamic web forms from certain kind of data schemas. Those schemas allows you to define multiple type of validations including error messages. They also allow to have kind of union type, so effectively I have written code, which has something like the following procedures:
- validate_all_of(...)
- validate_any_of(..)
and combine those in more like a tree logic to get final result of validation. The original structure is not possible to be used like this.

The second thing is I wanted to use validation functions, which are validating individual value/array elements, instead of whole array as such, that's why I have introduced this special setting for individual validation

A complex example:
- Imagine nicegui select element with multiple and user-input option and you wish to:
  - validate all elements individually by some rules
  - highlight values that doesn't pass with some reasonable error message
  - validate combined value/array with some additional rules (min, max elements....)
  - highlight whole select element that something is wrong with some more general but still reasonable error message

For this purpose I have created special class multiselect in my project, which extends nicegui select and uses those two new features..

And the last reason for adding "error.setter" is that I had case, when I needed to validate the value but only under very specific circumstances, which can be achieved only after certain actions the value is being changed/evaluated/validated, and I still wanted to show the result to end-user by modifying the error property. So this kind of validations are being done outside of nicegui, but I needed to forward the result back to nicegui like this

Hope it helps

**Comment by falkoschindler** [comment]
Ok, I just looked into the code and took some notes what changed:

- `validation` can now be
	- a `List[Callable[..., Tuple[bool, str]]]` or
	- a `Dict[str, Callable[..., bool]]`
    We will need to adjust the type annotation in validation elements like `ui.input` and so on, but let's do that later.
- You added the flag `_validate_individually` and the method `set_validate_individually`. I would simply use a public attribute `validate_individually`. But that's just a detail.
- You added a setter for the `error` property and the methods `_set_error_message` and `_clear_error_message`. I wonder with we need all three of them.
- And you added `_validate_single_value` which is used by `validate` in two difference branches.

I still have difficulties to understand the use case:

- The type `List[Callable[..., Tuple[bool, str]]]` might be useful for generating dynamic error messages like "List item 3 is 2 characters too short".
- But why do we need `_validate_individually`? Can't we pass in a validation function that loops over an array if the `value` happens to be an array?

Can you, please, share some user code that demonstrates how to use these new features? It would help me to understand the exact requirement. We will need a demo for the documentation anyway. Thanks!

**Comment by steweg** [comment]
You are right, there is no need to have _validate_individually. Even in my project we are no longer using it this way.

For the validation. Let's consider easy the following use-case:
 - Let's have a field A, which can be either number or string (in data schema this will be type `union`)
 - If A as number, there is condition that A must be from `2 to 60`
 - If B is a string, there is condition that A must have pattern [a-zA-Z0-9]+
So the code will do something like this:
```
#!/usr/bin/python3
import re
from typing import Optional, Any, List, Callable, Tuple
from nicegui import ui

def validate_range(value: Optional[str],
        range_min: int,
        range_max: int
        ) -> Tuple[bool, Optional[str]]:
    val = None
    try:
        val = int(value)
    except ValueError:
        return False, 'Value is not a number'
    if val < range_min or val > range_max:
        return False, 'Value is not within the range'
    return True, None

def validate_pattern(value: Optional[str],
        pattern: str
        ) -> Tuple[bool, Optional[str]]:
    if value is None:
        return True, None
    ret = bool(re.fullmatch(pattern, value))
    err_msg = None if ret else 'Value is not matching pattern'
    return ret, err_msg

def validate_any_of(value: Any,
        validations: List[Callable[[Any], Tuple[bool, Optional[str]]]]
        ) -> Tuple[bool, Optional[str]]:
    msgs = []
    for v in validations:
        ret2, msg2 = v(value)
        if ret2:
            return True, None
        msgs.append(msg2)
    return False, 'Value is not matching any of embedded validations with the following errors: ' + ', '.join(msgs)

validations = [
    lambda value: validate_range(value, 2, 60),
    lambda value: validate_pattern(value, '[a-zA-Z0-9]+')
    ]

ui.input(label='Test input', validation = [lambda value: validate_any_of(value, validations)])
ui.run()
```

**Comment by steweg** [comment]
Maybe just an idea would be change the type of validation as follows: `Union[Callable[..., Tuple[bool, str]], Dict[str, Callable[..., bool]]]` and let the user to write his own validation_all_of, instead of implicit behavior of List[...].

**Comment by falkoschindler** [comment]
Ok, I think focussing on the new kind of validation functions is a good idea. But I've got a few more questions:

1. What is the purpose of the string replacements in `set_error_message()`? I tried
    ```py
    ui.input(label='Test input', validation={
        'Value is\ntoo short': lambda value: len(value) >= 3,
    })
    ```
    but the line break doesn't work. So why replacing `\n`?
2. Replacing `"` seems reasonable to allow for double quotes within the error message. But it's probably easier to write the `_prop` dictionary value directly instead of using the public `.prop()` method:
    ```py
    self._props['error-message'] = message
    self.props('error')
    ```
3. Should `set_error_message` and `clear_error_message` really be public? I mean, it looks ok, but we should be sure that the user can't mess up the internal state by calling these methods.
4. And I'm wondering if the new validation functions could return an `Optional[str]` instead of a tuple. So they basically would return the error message - if there is any.

**Comment by steweg** [comment]
Hi, sorry for late reply....
1. & 2. Ok, removed and used direct assignment to _prop as suggested
3. Well my use-case is that I have set of validation rules, which are run when the value of element is changed, but I also have set of rules, which validate that value is meeting certain conditions related to other elements values. The second set of rules can be triggered only after specific events, therefore this logic must be done outside of element. But it make sense to allow re-using of error message display mechanism by allowing external validators to use such public methods. Of course external validators must be aware that the result can be override by calling public `validate` method etc...
4. I agree. I have also updated validation definition to provide Dict (old-way) or Callable (new-way/single validation function). It doesn't make sense to force user to always provide List. If user needs to use List and a new-way, user can define its own validate_all_of function

**Review by falkoschindler — APPROVED** [review]
Thanks, @steweg! I added a pytest and a demo for the documentation. Now the PR is ready to merge. 🙂

**Pull request merged**
