### PR TITLE
fixing navigation links behind "reverse proxy with subpath"

### PR DESCRIPTION
**Pull request by rodja**
Navigating between pages is currently not working in all cases when serving NiceGUI behind a reverse-proxy like NGINX or Traefik. Let's take our [nginx_subpath demo](https://github.com/zauberzeug/nicegui/tree/main/examples/nginx_subpath) as an example:

https://github.com/zauberzeug/nicegui/blob/971c577c40ce2bc01f97e56e7e94c35d38d42acc/examples/nginx_subpath/app/main.py#L4-L17

On the subpage the back button does not work as expected because the `ui.open()` is not aware about the url prefix set by the proxy.

Also the link on the main page must be relative (eg. no leading `/`) because otherwise we would link to http://localhost/subpage instead of the intended http://localhost/nicegui/subpage/.

### CODE REVIEW

**Comment by rodja** [comment]
Fixing the behaviour for `ui.open` was easy. But I do not have a good idea on how to solve the adaption of `href`. Ideally we would modify the href somehow while applying the prop in Vue. We can not do it in Python because of our auto-index client which serves content to multiple browser tabs which potentially have different subpath prefixes.

**Comment by rodja** [comment]
We still have no good approach to update the hrefs. Re-Introducing the `<base>` tag is not an option I think (see https://github.com/zauberzeug/nicegui/pull/188#issuecomment-1336313925).

**Comment by rodja** [comment]
Maybe we implement `ui.link` as an custom element...

**Comment by falkoschindler** [comment]
Strange. Selenium doesn't find the new links. Even though they look identical in the DOM, a simple test like the following fails:

```py
ui.link('link to subpage', '/sub')
screen.open('/')
screen.should_contain('link to subpage')
```

**Comment by rodja** [comment]
The XPath in our "find" method was not optimal. As ChatGPT explained to me:

> The contains() function expects two arguments of type string, but text() returns a node-set (multiple text nodes) rather than a single string. When contains() receives a node-set, it only considers the first node in the set, which can cause issues if there are multiple text nodes.

**Comment by falkoschindler** [comment]
Awesome! My discussion with ChatGPT wasn't that fruitful...

**Pull request merged**
