### PR TITLE
Providing a nice interface to simplify storing general and user specific data

### PR DESCRIPTION
**Pull request by rodja**
This PR started as an an attempt to make session data more accessible, as discussed in #732.
But it grew a bit larger after I recognized (again) that the session store can not be updated after the the response has been send to the browser. Therefore this PR also introduces a simple json based persistent storage on the server for each individual user and a general storage space shared by all users.

# ToDos

- [x] make the session secret configurable
- [x] allow disabling the the `SessionMiddleware` from being registered
- [x] update authentication example to use new app.storage 
- [x] change session documentation to `app.storage` with own subpage
- [x] fix other tests (a lot of them seems to be broken; but why?)
- [x] only write data to disk if something has changed?
- [x] fix tests (again)
- [x] save each user's data into a separate file
- [x] support for auto-persisting nested dicts, lists and set (separate pull-request with ObservableDict?)

### CODE REVIEW

**Comment by rodja** [comment]
The session store can not be updated after the the response has been send to the browser because it is (and should be) a http-only cookie. Thats why I have now introduced a server side persistent storage which also works after the client connection is established:

```py
@ui.page('/')
async def page(client: Client, delayed: bool = False):
    if delayed:
        await client.connected()
    app.storage.individual['count'] = app.storage.individual.get('count', 0) + 1
    ui.label().bind_text_from(app.storage.individual, 'count')
```

By default on shutdown and every ten seconds modified data is written to disk and automatically loaded on startup. The user is still identified via the session cookie.

In rare cases it may be better to directly store something in the session cookie. This can be done like this

```py
@ui.page('/')
def page():
    app.storage.browser['count'] = app.storage.browser.get('count', 0) + 1
    ui.label().bind_text_from(app.storage.browser, 'count')
```

And because everything was in place, I also created a general persistent storage which is shared by all users:

```py
@ui.page('/')
def page():
    app.storage.individual['count'] = app.storage.individual.get('count', 0) + 1
    app.storage.general['count'] = app.storage.general.get('count', 0) + 1
    ui.label(f'individual: {app.storage.individual["count"]}')
    ui.label(f'general: {app.storage.general["count"]}')
    ui.button('backup', on_click=app.storage.backup)
```

**Comment by rodja** [comment]
I renamed `app.storage.individual` to `app.storage.user` which feels more natural when using it. See this adapted auth example:

https://github.com/zauberzeug/nicegui/blob/7ca577e3270b643ab667c7198ccfe9d13c269ea2/examples/authentication/main.py#L8-L42

**Comment by rodja** [comment]
@frankhuurman 

> it handles the requests logic so that two users can independently use the NiceGUI application without getting in the way of the session of the other

Exactly. As an add-on there is also `app.storage.general` which can be used as a simple persistence shared between all users. For example to save the state of a board game like chess which needs to be accessed by multiple users.

> Can I donate to the NiceGUI project somewhere?

Not yet. The capability has been prioritized down in favour of more features and general niceness 😉
But we plan to do something in this direction before the summer is over.

**Review by falkoschindler — APPROVED** [review]

**Comment by amks1** [comment]
@rodja This is awesome. Would it be too difficult to add another dict for the session too? I mean one for each browser tab?

**Comment by OpenSourceIronman** [comment]
> The capability has been prioritized down in favour of more features and general niceness 😉
> But we plan to do something in this direction before the summer is
Why not turn on GitHub Sponsorship? I would love to donate $50 to the repo / project now, and probably closer to $100 per year as I use this for commercial purposes in the next 3 to 4 months. 

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

**Comment by rodja** [comment]
@amks1 I created a separate feature request https://github.com/zauberzeug/nicegui/discussions/1308 do discuss this separately.

@OpenSourceIronman setting up "GitHub Sponsorship" is really easy. But our main concern is the tax stuff which comes with it. It can easily be more expensive to do the paperwork than what we would receive from the community. But we are still seeking the best way forward.

**Pull request merged**
