### PR TITLE
Add viewport meta element

### PR DESCRIPTION
**Pull request by jfroco**
Add viewport <meta> element to the head of the rendered page. It could be disabled setting 'viewport' global variable or at page level.

Ref: Issue #274

### CODE REVIEW

**Comment by falkoschindler** [comment]
Thanks for the PR, @jfroco!
The code changes look very thorough and should be working nicely. But once we are here, we think it would be better to make `viewport` of type `str` with default value `width=device-width, initial-scale=1`. So `viewport` basically behaves like `title` with the default value defined once in `ui.run` and once in `ui.page`.

**Comment by jfroco** [comment]
I understsand.
Do you want me to create the pull request? Or are you going to do it?
Please let me know.
Best regards.

**Comment by falkoschindler** [comment]
@jfroco It would be great if you could update this PR. Thanks!

**Comment by rodja** [comment]
Hey @jfroco, are you planning on updating this PR in the next few days? We would really love this feature to be part of 1.1.4.

**Comment by jfroco** [comment]
> Hey @jfroco, are you planning on updating this PR in the next few days? We would really love this feature to be part of 1.1.4.

Yes, of course. I'm planning to create a new PR tomorrow. Best regards.

**Pull request closed without merging**
