### PR TITLE
Alternative implementation for ui.use_state

### PR DESCRIPTION
**Pull request by falkoschindler**
This PR is based on the idea of PR #1438 and the feature request #1410.

In contrast to a new `reactive` decorator and lots of nested functions, this PR builds upon the existing architecture of `ui.refreshable`. It extends `RefreshableTarget` with its current instance and a reference to the corresponding `refreshable`. Furthermore it adds a list of local variables as well as an index to the next variable to read from this list.

The `use_state` function is rather simple: Get the current instance of `RefreshableTarget` (the one which is currently evaluated), read the `value` from the list of `locals` (or append it if this list just being initialized), create a `set_value` function that can update this list item and calls `refresh()` and finally increment the `next_index`.

This is just a first draft. I haven't considered async functions yet. There might be issues when multiple async refreshables run in parallel and the `current_target` gets mixed up. But maybe be can solve this using task-specific target instances like we do for our slot stacks.

---

Poll: #1489

### CODE REVIEW

**Comment by falkoschindler** [comment]
Some test code:

```py
@ui.refreshable
def counter():
    count, set_count = ui.use_state(0)
    color, set_color = ui.use_state('black')
    ui.label(f'Count: {count}').classes(f'text-[{color}]')
    ui.button('Increment').on('click', lambda: set_count(count + 1))
    ui.input('Color', value=color).on('keydown.enter', lambda e: set_color(e.sender.value))

counter()
counter()
```

**Comment by qingant** [comment]
> Some test code:
> 
> ```python
> @ui.refreshable
> def counter():
>     count, set_count = ui.use_state(0)
>     color, set_color = ui.use_state('black')
>     ui.label(f'Count: {count}').classes(f'text-[{color}]')
>     ui.button('Increment').on('click', lambda: set_count(count + 1))
>     ui.input('Color', value=color).on('keydown.enter', lambda e: set_color(e.sender.value))
> 
> counter()
> counter()
> ```

cool, thanks @falkoschindler . I will have a deep look into this tonight or tmr.

**Comment by qingant** [comment]
HI @falkoschindler sorry for the late reply. I tested it with couple of cases, the implementation sounds right to me and looks like behavior same as my implementation.

the only concern I can think of , as you mentioned, is about the behavior when there are concurrent visits to current_target. It's hard for me to understand everything around this, but I assume we will do the context management (assign right current_target when the callback was called) somewhere. I am perfectly good if we are sure we do it right.

It seems that we are agreed on the UI design (decorator to make a function reactive, use_state to get handler of the state). So it's actually not super important how we implement it as we will always be able to change the implementation internally if necessary.

So I would suggest we use a different name from `refreshable` even with this implementation because:
1. from semantic perspective, it's actually not (only)  "refreshable", `component` or `reactive` would be better name for everyone who is from a react like framework
2. not necessarily use one name for two things (I think they are tow things in semantic)

Actually the semantic of `refreshable` is a little strange for me as an user as `refresh` is called on the function decorated by refreshable decorator, not the instance  which confused me how it will behave when there is multiple instances of a same `refreshable function ` ? which might add some extra complexity in the future to maintain the original `refreshable` semantic and the reactive `refreshable` semantic.
```python
import random
from nicegui import ui

numbers = []

@ui.refreshable
def number_ui() -> None:
    ui.label(', '.join(str(n) for n in sorted(numbers)))

def add_number() -> None:
    numbers.append(random.randint(0, 100))
    number_ui.refresh()

number_ui()
ui.button('Add random number', on_click=add_number)

ui.run()
```

**Comment by pythonormen** [comment]
Would this be a step towards being able to use refreshable ui.table and easier keep selection, pagination etc?

**Comment by falkoschindler** [comment]
@pythonormen Unfortunately not. `ui.refreshable` would still remove and recreate its content. So user state like selection and pagination would be lost. 😕

**Comment by falkoschindler** [comment]
I created a poll https://github.com/zauberzeug/nicegui/discussions/1489 to discuss how the API should look like.

**Comment by CrystalWindSnake** [comment]
@falkoschindler I believe that the update of state data does not necessarily require the component to be rebuilt. There seems to be a lack of semantics for monitoring responsive data. Here is a basic implementation using ex4nicegui.

```python
import pandas as pd
from nicegui import ui
from ex4nicegui.reactive import rxui
from ex4nicegui import on, to_ref, ref_computed, effect

# view model part
count = to_ref(0)
color = to_ref("black")

color_text = ref_computed(lambda: f"Count:{color.value}")
color_class = ref_computed(lambda: f"text-[{color.value}]")


@ref_computed
def table_data():
    return pd.DataFrame(
        {"var name": ["count", "color"], "value": [str(count.value), color.value]}
    )


def plus_count(value=1):
    count.value += value


def set_color(value: str):
    color.value = value


# ui part
count_label = rxui.label(count)


# you can also use effect here to implement automatic capture
# @effect
@on(color_class)
def on_color_changed():
    count_label.classes(color_class.value)


ui.button("Increment").on("click", plus_count)
rxui.lazy_input("Color", value=color)

# The data source of the table will be completely updated each time the data changes.
rxui.aggird.from_pandas(table_data)


# Precise update of table data
other_table = ui.aggrid.from_pandas(table_data.value)


@effect
def update_table():
    other_table.options["rowData"][0]["value"] = str(count.value)
    other_table.options["rowData"][1]["value"] = color.value
    other_table.update()
```

Its basic principle is just to monitor responsive objects, using the event binding of nicegui components to achieve responsive updates.

**Comment by falkoschindler** [comment]
@CrystalWindSnake [ex4nicegui](https://github.com/CrystalWindSnake/ex4nicegui) is definitely impressive. But what sounds simple ("just to monitor responsive objects"), is a pretty complex undertaking. You have to wrap almost every class initializer and every method to handle the case of a responsive argument. And it messes with the IDE (regarding type checking and code completion) and introduces code duplication which we try to avoid as much as possible. Therefore we're looking for a tradeoff that achieves something similar with much less effort.
But it is important to be aware of the difference: `ui.refreshable` and `ui.state` will _replace_ the UI on every change, which concepts like ex4nicegui only update what is necessary. It's great to have both options!

**Comment by CrystalWindSnake** [comment]
> @CrystalWindSnake [ex4nicegui](https://github.com/CrystalWindSnake/ex4nicegui) is definitely impressive. But what sounds simple ("just to monitor responsive objects"), is a pretty complex undertaking. You have to wrap almost every class initializer and every method to handle the case of a responsive argument. And it messes with the IDE (regarding type checking and code completion) and introduces code duplication which we try to avoid as much as possible. Therefore we're looking for a tradeoff that achieves something similar with much less effort. But it is important to be aware of the difference: `ui.refreshable` and `ui.state` will _replace_ the UI on every change, which concepts like ex4nicegui only update what is necessary. It's great to have both options!

I subscribe to your opinion, it is not suitable to implement a complete set of complex reactive mechanisms in nicegui.

**Review by rodja — APPROVED** [review]

**Pull request merged**
