### PR TITLE
Color background of color_input

### PR DESCRIPTION
**Pull request by adosikas**
This changes the background of the `color_input` buttons to preview the selected color.

To allow the icon to stay visible regardless of selected color, a white border is added around it.

grafik

As suggested in #1390, this is implemented as `preview=True` parameter (default enabled).

### CODE REVIEW

**Review by falkoschindler — COMMENTED** [review]
Nice! I really like this PR. Thanks, @adosikas!

I just think `preview: bool = False` should be the default - at least for now. We could indicate an upcoming breaking change for v1.4 like we did [here](https://github.com/zauberzeug/nicegui/blob/99854b878e868fd30de313512cad24b8de89392d/nicegui/page_layout.py#L29). But maybe the look of a colored picker button isn't for everyone. @rodja, what do you think: Should this preview be the default (eventually)?
Screenshot 2023-08-22 at 22 30 28

**Comment by rodja** [comment]
@falkoschindler I would be ok with activating the preview by default right away. It wont 'break' anything in a classical sense and can easily be deactivated.

**Comment by adosikas** [comment]
One thing I could see against enabling it by default is that it allows injecting arbitrary strings into the CSS, for example by entering "#fff; display:none".

But I am not sure if that is a concern.

**Comment by falkoschindler** [comment]
@adosikas That's a good point. I can't come up with a potential attack vector, but checking for ";" might be an easy thing to do to prevent abuse.

Apart from that, @rodja and I agreed on _not_ making the preview the default, since a secretly appearing bold colorful circle might not be everyones taste. And by setting `preview: bool = False` we can easily extend it later to something like `preview: Union[bool, Literal['button-background', 'small-box', 'text-color']] = False`. See [here](https://www.grapecity.com/wijmo/docs/Topics/Input/InputColor/InputColor) for an illustration of the "small-box" idea.

**Pull request merged**
