### PR TITLE
Update Plotly to 2.20.0.

### PR DESCRIPTION
**Pull request by dclause**
As of nicegui 1.2.0 the milestone was to update all dependencies to the latest. 
plotly was left over at version 2.18.2 as detailled [here](https://github.com/zauberzeug/nicegui/issues/524#issuecomment-1476203713).

Not sure if a particular reason or a leftover. Latest version is 2.20.0 and seems to work like a charm, hence this PR.

### CODE REVIEW

**Comment by falkoschindler** [comment]
Oh, that's unfortunate. I scraped the version number from their website:

Screenshot 2023-03-21 at 09 34 45

Apparently this is not the latest version. Do you have an online resource I could use in fetch_dependencies.py?

Although we planned to update dependencies only for releases like 1.2.0, 1.3.0, ... I think it doesn't hurt to update plotly within the 1.2.1 milestone. Do you agree, @rodja?

Note that we should keep track of the plotly version in DEPENDENCIES.md once it is released.

**Comment by rodja** [comment]
> it doesn't hurt to update plotly within the 1.2.1 milestone

@falkoschindler yes, we should do it

**Comment by dclause** [comment]
@falkoschindler 
I retrieve directly the latest versions available from the NPM repo packagist using npm.py from the PR #565

**Comment by dclause** [comment]
@falkoschindler side question : what makes 1.2.1 ready for release ? Would this PR suffisiant to justify 1.2.1 ? Is there a release calendar that dictates a date, or maybe a roadmap with milestone for each soon to be releases ?

**Comment by falkoschindler** [comment]
@dclause Good question. We try to organize issues and PRs into [milestones](https://github.com/zauberzeug/nicegui/milestones). But can always sneak a release in between and simply postpone all other tasks. I'd just like to coordinate the 1.2.1 release with @rodja, since he's working on #582, which is also kind of urgent and would nicely fit into 1.2.1 as well.

**Pull request merged**
