### PR TITLE
update menu_and_tabs example to use tab_panels

### PR DESCRIPTION
**Pull request by xec-abailey**
Pretty self-explanatory! Was checking out the source code while working on a new project that was using tabs. Looked at the menu and tabs example and saw it was outdated. Updated it to use tab_panels. 

Cheers

### CODE REVIEW

**Comment by xec-abailey** [comment]
Before:

before

After: 

after

**Comment by xec-abailey** [comment]
Issue #1013

**Review by falkoschindler — APPROVED** [review]
Thanks for spotting this outdated example, @xec-abailey!
I just made some minor adjustments. From my point of view this is ready to merge into main. 🙂

**Comment by xec-abailey** [comment]
> Thanks for spotting this outdated example, @xec-abailey! I just made some minor adjustments. From my point of view this is ready to merge into main. 🙂

Thanks for that @falkoschindler , I will make sure to stick to that for the (hopefully) future ones! Did have a quick question though - I looked through issues and didn't see one on getting devcontainer set up for the dev environment. Was wondering if y'all had considered it or were purposely avoiding it for a reason? 

Feels like it would make the developer setup easier and make it easier to contribute?

Cheers!

**Comment by rodja** [comment]
@xec-abailey instructions for devcontainer setup in [CONTRIBUTING.md](https://github.com/zauberzeug/nicegui/blob/main/CONTRIBUTING.md) would be great. We are not using them very actively our self but there is much value for the community. Are you willing to create a pull request?

**Pull request merged**
