### PR TITLE
Avatar: added QAvatar component

### PR DESCRIPTION
**Pull request by Diegiwg**
I don't know how to Bind Quasar properties to class properties, so I ended up inventing qstyle and qcontent.

I hope that, if you agree to add this component, you map the qcontent and qstyle to the component's properties.

### CODE REVIEW

**Comment by Diegiwg** [comment]
I was testing a way to expose all Quasar properties, in one namespace, like we are doing with .tailwind for styles.

But I realized that it is very different from Nicegui's current API, so I redid it as you suggested, adding the option to change the values ​​of these properties in the element's constructor.

**Comment by falkoschindler** [comment]
Great! I reviewed and improved the implementation a bit:

- We need to use `Optional` instead of `... | None` for compatibility with Python 3.7.
- For consistency I replaced `"` with `'` for quoting strings.
- The props `square` and `rounded` are not mutally exclusive but can be combined. Therefore I added them separately.
- We usually enforce keyword arguments with `*` in the parameter list to avoid confusion when passing multiple unnamed arguments.

In my point of view, this is ready to be merged. @rodja What do you think?

**Comment by rodja** [comment]
I like it!

**Comment by rodja** [comment]
The NiceGUI logo used in one of the examples was distorted. In https://github.com/zauberzeug/nicegui/commit/abe246371039da481bde0cb91be5bb0939763b3c  I added a square version of the logo which is not yet deployed to https://nicegui.io. This will be done when releasing v1.1.10.

**Pull request merged**
