### PR TITLE
Added functions to get client data to AgGrid element

### PR DESCRIPTION
**Pull request by BrianLandry**
When the client edits a cell in AgGrid the data is not automatically synced to the python dictionary backing the AgGrid element. To obtain that data this PR adds a helper function to the AgGrid element that executes javascript to obtain the rowData present on the client.

This PR would address [this question](https://discord.com/channels/1089836369431498784/1110004795021991997/1110335181908344864) from Discord and also is something I am using in my own work.

I plan to add tests, but am struggling to get Selenium working right now. I wanted to open this PR in the meantime to make sure there was interest in this feature. If so I'll work on getting the tests together.

### CODE REVIEW

**Comment by falkoschindler** [comment]
@BrianLandry Thanks a lot for this pull request! I finally found the time to have a look into it.

The idea sounds very reasonable. Unfortunately, however, it doesn't seem to work. This is what I'm experimenting with:

```py
grid = ui.aggrid({
    'columnDefs': [{'headerName': 'Name', 'field': 'name', 'editable': True}],
    'rowData': [{'name': 'Alice'}, {'name': 'Bob'}, {'name': 'Carol'}],
})

async def get_data():
    print(await grid.get_client_data())

ui.button('Get data', on_click=get_data)
```

But it always prints the original data, ignoring any edits.

**Comment by BrianLandry** [comment]
nteresting. I’ll try to dive in this weekend and see whats up. I am using this code regularly and it’s definitely working. So its either a issue with how i moved it over to this code base. Or some more tricky setup specific bug.

**Comment by BrianLandry** [comment]
If I edit a cell, and then click the "Get Data" button I replicate your behavior. Hopefully, this is what was occurring on your end. This is because by default the AgGrid has the parameter `stopEditingWhenCellsLoseFocus` ([docs](https://www.ag-grid.com/angular-data-grid/cell-editing-start-stop/#stop-editing-when-grid-loses-focus)) set as False. This means the cell is still being edited, and the client doesn't have the updated value yet. This is an annoying default I don't expect people to find, and I think the behavior described here will be common and should be addressed.

To address this I can think of three options:

1. Keep current behavior and add a suggestion to change `stopEditingWhenCellsLoseFocus` to true in the comments of `get_client_data`.

2. Do # 1, but also check the value of `stopEditingWhenCellsLoseFocus` and if it is false log a warning describing this behavior but continue.

3. Add `getElement({self.id}).gridOptions.api.stopEditing();` ([docs](https://www.ag-grid.com/javascript-data-grid/cell-editing-start-stop/)) to the javascript in `get_client_data`. This fixes the issue, but seems to be working around a feature option already in AgGrid, when instead the user should just set the AgGrid option correctly.

I'm leaning towards # 1. I don't think niceGUI should try to address bad defaults in AgGrid, even if it is causing a painpoint when using niceGUI, but it would be great to hear your thoughts.

**Comment by falkoschindler** [comment]
Thanks for the clarification, @BrianLandry! That might have been the problem. I added a note about `stopEditingWhenCellsLoseFocus` to the documentation.
Now everything works as expected. Let's merge it! 🙂

**Pull request merged**
