### PR TITLE
Issue #600: fix DOM mutation issue regarding vue in-place-patching ti…

### PR DESCRIPTION
**Pull request by dclause**
See #600 600

### CODE REVIEW

**Comment by falkoschindler** [comment]
This looks really nice! I wonder how this fixes the bug... But an empirical validation will suffice, I guess. 🤷‍♂️

Originally I used a nested source tag like in [this example](https://www.w3schools.com/tags/tag_audio.asp). Now I notice that `audio` also has a `src` attribute.
But there is no `type` attribute in `audio` nor in `video`. Is your code still valid?

**Comment by dclause** [comment]
@falkoschindler You are right, _type_ is needed in the <source> tag, which is used for multi source audio case which is not our case. Looks look like with mono src <audio> and <video> infer the type based on src according to the documentation. We should be fine with it. It is even easier to use for end-user not to specify a mime-type.
How about fully removing this from the audio and video element ? that would break the API though, but why asking it in the API if not used...
What's your opinion here ?

**Comment by falkoschindler** [comment]
Ah, so the `type` prop is basically ineffective in our case, right? We don't offer multi-source audio or video. Should we simply drop it?

**Comment by dclause** [comment]
You tell me. From the vue component point of view, it is now useless. But it is currently a parameter of the audio.py component, so I guess removing it would be an API break ? Are you OK with doing that ?

**Comment by rodja** [comment]
@dclause maybe we could create a 1.3 branch where we remove the `type` property to not force a new minor release now...

**Comment by falkoschindler** [comment]
I'd suggest to remove `type` from the JS component, as it was basically ineffective before because there was only one `source` tag. In Python I would show a deprecation warning if someone passes a value for `type`. I can do that.

**Comment by falkoschindler** [comment]
I just pushed my proposal. @rodja Let's discuss it on Monday.

@dclause I assume I can remove the `ref="videoPlayer"` in video.js since it's currently not used.

**Comment by dclause** [comment]
Hi @falkoschindler, 
I just checked the branch: looks good to me. I guess it can be either merged as is to main for next release to unlock the personn at #600, and/or prepared also for 1.3 with a full `type` parameter removal. 
As @rodja suggested, this can be "pre-merge" in a 1.3 release branch.

**Pull request merged**
