### PR TITLE
Chat with AI example

### PR DESCRIPTION
**Pull request by wptmdoorn**
After discussion with @rodja on the Discord server he thought it would be nice to include a 'chat with AI' example in the standard examples section.
This PR provides the code for that. 
Few take-aways:

- I aimed to conserve most of the `examples/chat_app` code
- It uses `langchain` to query OpenAI GPT-3.5, langchain makes most sense to me since it's a general purpose LLM library.
- To provide an API key I ought now to do it within the script using `os.environ['OPENAI_API_KEY'] ....` with a small disclaimer in the chatbox if the user didn't input this. An `.env` file seems overkill to me.

Happy to hear your feedback, thank you :)

### CODE REVIEW

**Comment by falkoschindler** [comment]
Thanks a lot for this great example, @wptmdoorn!

I just reviewed the code and made some minor changes. E.g. I decided to remove avatars and timestamps as they are rather irrelevant here and are already demonstrated in the Chat App example.

What bugs me a little is the warning "You are trying to use a chat model. This way of initializing it is no longer supported. Instead, please use: `from langchain.chat_models import ChatOpenAI`". But I couldn't get it working with `ChatOpenAI`.

**Comment by wptmdoorn** [comment]
You are right, I am sorry I didn't notice that warning. 
I deliberately chose for `OpenAI` module to be able to use `llm.agenerate(..)` (async version). I will update the code accordingly!

**Comment by wptmdoorn** [comment]
First of all, thanks for the little modifications - it learns me a lot :) the spinner looks neat! I wanted something like that but could not directly find such functionality. 

I replaced the `OpenAI` call to a `ConversationChain(llm=ChatOpenAI(...))` call. This does include some extra complexity of LLM chain (in the `ConversationChain` call) but might be the most appropriate for this example? As such, we keep some async functionality an as an additional advantage is that the chain now handles conversation memory, so it feels more like chatting (e.g. see below):

Screenshot 2023-05-04 at 16 32 24

Only downside is that it's a little bit more complex, but I guess whenever wants to learn about LLMs and stuff they have to dig in anyway. Happy to hear your feedback.

**Comment by falkoschindler** [comment]
Wow, thanks for the quick fix, @wptmdoorn!
I'm learning as well. Never used OpenAI in Python. 😊
Ready to merge!

**Pull request merged**
