### PR TITLE
feat: Implement Ag Grid Dynamic Functions

### PR DESCRIPTION
**Pull request by aersam**
Fixes https://github.com/zauberzeug/nicegui/discussions/1420 
Fixes https://github.com/zauberzeug/nicegui/discussions/1468

### CODE REVIEW

**Comment by aersam** [comment]
Actually the `recursive_convert_dynamic` should be in some utils js. Also it could be more recursive. As this might imply lots of new objects, might be good to have this behavior behind a flag in general

**Comment by aersam** [comment]
> Actually the `recursive_convert_dynamic` should be in some utils js, I think that concept is currently missing.
> 
> Would be nice if we could place such generic utils in a folder and just import it: `import { recursive_convert_dynamic } from "/utils/dynamic_obj.js"; `

Found a way to do exactly this, see last commit. I will now stop committing so that someone can review

**Comment by falkoschindler** [comment]
Hi @aersam, thanks for this pull request!

I just reviewed your code and wanted to commit some minor changes here and there. But now I noticed that I can't push onto your PR. Would it be possible to get permissions to do so? Thanks.

Apart from that, I like the idea of moving generic utilities into separate files. But on the other hand, if these functions are only used by `aggrid.js`, they could stay there as well. We could use them in `table.js` though. But there we probably don't need the less efficient recursion.

**Comment by aersam** [comment]
You should have permission now, hope I did it correctly

I think the utility function is something lot's of more complex components would benefit from, though it's currently only used by aggrid. I'm sure I'll be needing it somewhere else later on :)

**Comment by aersam** [comment]
For the recursion efficiency I don't think it's a concern if the object is not that large. However one could also add a flag like `allow_dynamic_properties` for such components to avoid it completely

**Comment by falkoschindler** [comment]
@aersam Thanks for the clarification.

Regarding the permission... I think it's easier to just allow "edits from the maintainers". Here is an instruction I just got from ChatGPT:

> **Via the Pull Request Interface:**
>
>- The author should navigate to the PR on the main repository.
>- Scroll down to the PR box where there's a list of checks, comments, and other details.
>- There should be a checkbox titled "Allow edits from maintainers." Ensure this is checked. If this checkbox is enabled, maintainers of the base repository can push changes to the PR branch.

**Comment by aersam** [comment]
> @aersam Thanks for the clarification.
> 
> Regarding the permission... I think it's easier to just allow "edits from the maintainers". Here is an instruction I just got from ChatGPT:
> 
> > **Via the Pull Request Interface:**
> > 
> > * The author should navigate to the PR on the main repository.
> > * Scroll down to the PR box where there's a list of checks, comments, and other details.
> > * There should be a checkbox titled "Allow edits from maintainers." Ensure this is checked. If this checkbox is enabled, maintainers of the base repository can push changes to the PR branch.

I don't find that button, maybe because I used an org repo. I made you a collaborator in the fork, hope that works :)

**Comment by aersam** [comment]
Aha, here we go: https://github.com/orgs/community/discussions/5634. seems allowing to update is not possible

**Comment by aersam** [comment]
Yes making it in place makes sense, but then I would not even copy the object as in Line 19 in table.js, unless there is really a good reason to do so. that's what I wanted to avoid as it would mean to copy the whole object structure anyway

**Comment by falkoschindler** [comment]
@aersam Oh, you're right! I though I couldn't modify the original `columns` because it is a prop. But apparently that's not the case. 🙂

**Comment by falkoschindler** [comment]
Great! I pushed my code review to a new branch, improved the recursive implementation and integrated it into table.js as well. All tests are green, so I merged into main. 🎉

Thanks again for your contribution, @aersam!

**Comment by aersam** [comment]
Thanks!

**Comment by aersam** [comment]
Do you have any idea when this will be released? Have some cool stuff waiting for this :)

**Comment by falkoschindler** [comment]
@aersam We'll probably release it with version 1.3.12 today.

**Pull request merged**
