### PR TITLE
Enable new_value_mode="add" for dict options

### PR DESCRIPTION
**Pull request by me21**
This pull request enables using new_value_mode="add" when options are dict.
My use case is displaying a list of people, allowing user to enter a new name. Naturally, there can be duplicates because people may have same name. But their internal ids are different.

This feature requires new_value_id_generator (a new parameter) to be not None. If it's None, previous behavior is retained.

---

See feature request #2462.

### CODE REVIEW

**Comment by falkoschindler** [comment]
Thanks for this pull request, @me21!
I'm still trying to understand the use case. Can you share a minimal example of how you would use the new feature? Why is "add" more useful than "add-unique" when used with a dictionary? Thanks!

**Comment by falkoschindler** [comment]
Sorry, I just noticed your example from #2462:

```py
from itertools import count

ui.select({1: 'Alice', 2: 'Bob'}, label='User', new_value_mode='add', new_value_id_generator=count(start=3, step=1))
```

**Comment by me21** [comment]
Well, suppose we have Alice and Bob in the list but I would like to add a second Alice. Would it work in add-unique mode?

**Comment by me21** [comment]
I added the capability to use the inserted value to generate an id for it. Please see `_new_id` function which is used from `_handle_new_value`.
The `new_id_generator` argument can be either None, an iterable, a callable or a generator. In two latter cases it accepts `value` to be passed into it to generate a new ID.
I think another check is needed when it's a callable to check whether it really expects an argument.

**Review by falkoschindler — CHANGES_REQUESTED** [review]
@me21 I just reviewed the code again after your recent changes, but it's not yet working as it should. I think you forgot to implement the "add" mode for dictionaries.

```py
options = {'a': 'A', 'b': 'B', 'c': 'C'}
select = ui.select(options, value='b', new_value_mode='add', new_id_generator=lambda _: time.time())
label = ui.label()
ui.timer(0.1, lambda: label.set_text(str(select.options)))
```

When adding "X", "Y", and another "X", the second "X" is ignored.

**Comment by me21** [comment]
I'm sorry for the delay, I must have missed the email notification about this. I will try to prepare an update this week.

**Review by me21 — COMMENTED** [review]
Added a commit to fix this.

**Comment by me21** [comment]
Hi @falkoschindler, sorry to bother you, but I'm not sure whether you saw any notification when I updated this PR.

**Comment by falkoschindler** [comment]
No worries, @me21. I just haven't found the time to look into it. 🙂

**Review by falkoschindler — APPROVED** [review]
Ok, I reviewed once again, added a simple pytest and fixed an edge case when the key generator yields a falsy key. Furthermore I chose to use the term "key" instead of "id".

@rodja Do you agree with the new API?
```py
options = {'a': 'A', 'b': 'B', 'c': 'C'}
select = ui.select(options, value='b', new_value_mode='add', key_generator=lambda value: f'{len(options)}-{value}')
ui.label().bind_text_from(select, 'options', lambda v: f'options = {v}')
```

**Comment by rodja** [comment]
Yes. Looks good 👍

**Pull request merged**
