### PR TITLE
Example for NiceGUI with ROS2

### PR DESCRIPTION
**Pull request by JensOgorek**
ROS2 examples with Docker functionality

### CODE REVIEW

**Comment by rodja** [comment]
The focus on just one example is great! Are the files in `tests/` really necessary?

**Comment by falkoschindler** [comment]
@rodja I think this is what ROS creates for you when creating a new node or package. But I'd vote for removing unnecessary files to reduce clutter and to focus on what is essential for this example. It's unlikely that anyone will miss them.

**Comment by JensOgorek** [comment]
Exactly, these files were created by `ros2 pkg create --build-type ament_python`. They are just some default tests.

**Comment by rodja** [comment]
I've tried running the turtlesim docker container on mac but there where errors with the `xcb` qt plugin. Even on Linux it's quite cumbersome to start the UI. Therefore I would favour a ROS2 example which only uses NiceGUI as a UI. That will be much simpler to start and use. Maybe build the turtlesim visualization directly with nicegui?

**Comment by JensOgorek** [comment]
The reason for the `xcb` to error is the active OS. The configuration is for Ubuntu systems. You can start the Docker with `docker compose up joystick_example` to just run the joysick part. You can start the turtlesim locally and still use the joystick. 
Also, I can look into creating multiple versions of the config for the different operating systems.
Getting the visualization out of the docker container is always cumbersome, that's just how docker is. Completely converting the turtlesim for this would defeat the purpose of using the turtlesim for this example, I think.

**Comment by rodja** [comment]
> Completely converting the turtlesim for this would defeat the purpose of using the turtlesim for this example, I think.

I would sacrifice the turtlesim in favour of a simpler, easier demo which shows the advantages of NiceGUI over qt and similar solutions.

> Getting the visualization out of the docker container is always cumbersome, that's just how docker is.

Exactly. That is one of the many advantages of using NiceGUI here...

**Comment by JensOgorek** [comment]
> I would sacrifice the turtlesim in favour of a simpler, easier demo which shows the advantages of NiceGUI over qt and similar solutions.
How about going back to minimal publisher with a custom message, that is put in with NiceGUI?

**Comment by rodja** [comment]
Closing in favour of https://github.com/zauberzeug/nicegui/pull/1083.

**Pull request closed without merging**
