### PR TITLE
Fix set_storage_secret

### PR DESCRIPTION
**Pull request by awfulness**
Set secret does not work with run_with, because in set_storage_secret function modifies globals.app (for run_with there should be app modification!).

### CODE REVIEW

**Comment by rodja** [comment]
Thanks for taking the time to create this pull request @awfulness. Can you elaborate a bit more on your observation that `app.storage` seems not to be working for you when using `ui.run_with`? In our FastAPI example we have already integrated the usage of `app.storage` to persistently toggle the dark mode:

https://github.com/zauberzeug/nicegui/blob/a464337f1861ac2292852cb17a4d1ecf9bada2eb/examples/fastapi/frontend.py#L13

And it works as expected...

**Comment by awfulness** [comment]
> Thanks for taking the time to create this pull request @awfulness. Can you elaborate a bit more on your observation that `app.storage` seems not to be working for you when using `ui.run_with`? In our FastAPI example we have already integrated the usage of `app.storage` to persistently toggle the dark mode:
> 
> https://github.com/zauberzeug/nicegui/blob/a464337f1861ac2292852cb17a4d1ecf9bada2eb/examples/fastapi/frontend.py#L13
> 
> And it works as expected...

The example above works, but it is run via bash. I use another way, I think it's much better (I can add such a way to the examples).

Here is an example of my file:
```
import uvicorn
from nicegui import ui, app
import nicegui
from fastapi import APIRouter

from fastapi import FastAPI


api = APIRouter()
ui_router = nicegui.APIRouter()


@api.get(path="/ping")
async def ping():
    return "pong"


@ui_router.page("/")
def show():
    app.storage.user['count'] = app.storage.user.get('count', 0) + 1
    print(app.storage.user['count'])
    ui.label('Hello, FastAPI!')


fast_app = FastAPI(
    title="Example",
    docs_url=f"/example/swagger",
    redoc_url=None,
    openapi_url=f"/example/api/openapi.json"
)
fast_app.include_router(router=api, prefix=f"/example/api/v1", tags=["API"])
fast_app.include_router(router=ui_router, prefix=f"/example/ui", tags=["UI"])


if __name__ == "__main__":
    ui.run_with(app=fast_app, storage_secret="test")
    uvicorn.run(fast_app)

```
It's enough to run it:
`python3 main.py`

I get an error when I access the page:
```
  File "PycharmProjects/NiceAndFast/main.py", line 15, in ping
    app.storage.user['count'] = app.storage.user.get('count', 0) + 1
  File "niceandfast-pnwG_Iik-py3.10/lib/python3.10/site-packages/nicegui/storage.py", line 112, in user
    if globals.get_client() == globals.index_client:
  File "niceandfast-pnwG_Iik-py3.10/lib/python3.10/site-packages/nicegui/globals.py", line 86, in get_client
    return get_slot().parent.client
  File "niceandfast-pnwG_Iik-py3.10/lib/python3.10/site-packages/nicegui/globals.py", line 82, in get_slot
    return get_slot_stack()[-1]
```

**Comment by rodja** [comment]
Interesting. When minimizing your example it works:

```py
import uvicorn
from nicegui import ui, app

from fastapi import FastAPI


fast_app = FastAPI()


@fast_app.get(path="/ping")
async def ping():
    return "pong"


@ui.page("/")
def show():
    app.storage.user['count'] = app.storage.user.get('count', 0) + 1
    ui.label().classes('text-4xl').bind_text_from(app.storage.user, 'count')


if __name__ == "__main__":
    ui.run_with(app=fast_app, storage_secret="test")
    uvicorn.run(fast_app)
```

I suspect some problem with the ApiRouter...

**Comment by rodja** [comment]
Ah yes. This works:

```py
import uvicorn
from nicegui import ui, app, APIRouter

from fastapi import FastAPI

router = APIRouter()
fast_app = FastAPI()


@fast_app.get(path="/ping")
async def ping():
    return "pong"


@router.page("/")
def show():
    app.storage.user['count'] = app.storage.user.get('count', 0) + 1
    ui.label().classes('text-4xl').bind_text_from(app.storage.user, 'count')


app.include_router(router=router, prefix=f"/ui", tags=["UI"])

if __name__ == "__main__":
    ui.run_with(app=fast_app, storage_secret="test")
    uvicorn.run(fast_app)
```

So in your example it should be enough to replace `fast_app` with the NiceGUI `app`:

```diff
- fast_app.include_router(router=ui_router, prefix=f"/example/ui", tags=["UI"])
+ app.include_router(router=ui_router, prefix=f"/example/ui", tags=["UI"])
```

**Comment by awfulness** [comment]
It's working! Thank you.
The only difference is that swagger doesn't have paths for ui, but I don't need them.
I'll close this this PR and create a new PR with an example of fastapi integration.

**Pull request closed without merging**
