### PR TITLE
enable new input in select, new-value-mode="add-unique"

### PR DESCRIPTION
**Pull request by artreven**
Hi,

My tiny PR to address #1045 . I added a parameter `add_new_unique_values: bool` to the `__init__` of `ui.select`, corresponds to `new-value-mode="add-unique"` in Quasar terms. Tests cover both single selection and `multiple=True`. Please, let me know if missed anything.

### CODE REVIEW

**Comment by rodja** [comment]
Thanks for the effort @artreven. Why do you think it's better than setting the quasar prop? It's only needed in quite specialized scenarios.

**Comment by artreven** [comment]
Thanks for feedback @falkoschindler !

I made the corresponding changes. I add an if-clause to check `isinstance(self.options, dict)` and handle properly. However, existing value in the options dictionary might be overwritten if the new input value is equal to an existing key. Is this acceptable?

For the sanity check, I am not sure what would be the best strategy: raise an Exception? I could not find an examples in the existing elements. Can I kindly ask for your suggestion?

**Review by falkoschindler — COMMENTED** [review]
Thanks for the update, @artreven!

I made some changes, mainly to the documentation. I also let the `new_value_mode` automatically set `with_input`, so the user doesn't have to deal with it. And I managed to combine the handling of new values.

It's still a work in progress and I'll probably continue tomorrow. Now that we support three "new value modes", we need to handle them correctly (see the TODO marker).

The whole feature turned out pretty complex. (Well, it was our idea to support multiple modes... 🫢) But I think we need to further extend the test cases. We have the following dimensions to check:
- single vs. multi select
- list vs. dict options
- add/unique/toggle mode
- and in each of these 2x2x3=12 configurations the user can use the dropdown or the input field.
Maybe we can parametrize the test cases, or at least part of the configuration.

**Comment by falkoschindler** [comment]
Wow, that got complicated. But I think it is working now. And the the new parameterized test should cover all cases.
What do you think, @artreven?

**Comment by falkoschindler** [comment]
By the way, I experimented with the following code:
```py
with ui.row():
    for new_value_mode in [None, 'add', 'add-unique', 'toggle']:
        for multiple in [False, True]:
            for option_dict in [False, True]:
                if option_dict and new_value_mode == 'add':
                    continue
                with ui.card():
                    ui.label(f'{option_dict=}')
                    ui.label(f'{multiple=}')
                    ui.label(f'{new_value_mode=}')
                    options = {'a': 'A', 'b': 'B', 'c': 'C'} if option_dict else ['a', 'b', 'c']
                    s = ui.select(options=options, multiple=multiple, new_value_mode=new_value_mode)
                    ui.label().bind_text_from(s, 'value', lambda v: f'value = {v}')
                    ui.label().bind_text_from(s, 'options', lambda v: f'options = {v}')
```

**Comment by artreven** [comment]
Hi @falkoschindler . Thanks a lot, this looks great!

**Pull request merged**
