### PR TITLE
FullCalendar Element

### PR DESCRIPTION
**Pull request by frankvp11**
Currently it's at the state where the element is working, however the documentation is not.
When I run the file websites/more_documentation/fullcalendar_documentation.py in it's current state, it works. However, when I comment out the last lines ( ui.run and main_demo()), and try to run the main.py file, it can't seem to find FullCalendar.
From the discord discussions, we believe this is because of a static file issue. 

Issues aside, in this current implementation, users can click on the events, add events "easily", and remove them aswell.
It also allows the user to choose their own options, a full list can be viewed here: https://fullcalendar.io/docs/view-specific-options
The basic ones though, are implemented in the documentation example.
Edit: One thing that I noticed is that I still need to remove the test_temp.py file (sorry about that, I will do that later today)

### CODE REVIEW

**Comment by falkoschindler** [comment]
Thanks, @frankvp11!

I reviewed the code, made some changes here and there, but can't get the local index.global.min.js to work. According to the developer console, it is properly loaded. Is it a timing problem? But even with a timeout of 500ms `FullCalendar` isn't defined... I'll have to look into it again later.

**Comment by falkoschindler** [comment]
By the way, I'm testing with this code:
```py
ui.fullcalendar({'initialView': 'timeGridWeek', 'events': [{
    'title': 'Work',
    'start': datetime.now().strftime(r'%Y-%m-%d 09:00:00'),
    'end': datetime.now().strftime(r'%Y-%m-%d 17:00:00'),
}]})
```

**Comment by frankvp11** [comment]
Yeah, so that's exactly what we've been trying to figure out in the discord aswell. Despite the fact that the local index.global.min.js is there, it still doesn't define FullCalendar. That's why we had added the static file to the html, however once we tried running the documentation it 'broke'

**Comment by frankvp11** [comment]
So, I "figured" out how to fix it. 
Essentially, adding the line 
```
export default FullCalendar
```
in the global.index.min.js fixed the issue. Then, in the fullcalendar.js file, I added the import (which is "scuffed" right now).
However,
with the scuffed nature of it out of the way, it does technically work?

**Comment by frankvp11** [comment]
I'm not to sure why it's failing a check...

**Comment by frankvp11** [comment]
Hey Falko,
Any ideas why my fork is failing the checks? Also, how can I fix the conflicting files?

**Comment by falkoschindler** [comment]
Sorry, @frankvp11, I haven't found the time to dig into this PR again. But it's on my list.

Just a few brief remarks:
- I'm not so sure about changing the third-party libraries. But it might be useful for debugging and could lead to a solution. Ultimately we would want to use original files though.
- Don't worry about the conflicting files. The whole documentation is undergoing a massive refactoring, some of which has already been pushed to the main branch for the 1.4.3 release. Since most files moved, there's now a conflict with your PR. But I can easily fix that later.

**Comment by frankvp11** [comment]
Thanks for the update, and I'll try to be more patient. 
I'll try and keep looking to see if any of the source files have the necessary "export default" commands in the mean time, and good to know about the documentation :+1:

**Comment by frankvp11** [comment]
One of the things that I've been trying to figure out (and struggling with) is the following:
```
import * as FullCalendar from "/_nicegui/1.4.0/libraries/f2236eb73ecd4b599de1d20d128079e5/index.global.js";
```
The reason I am trying this is because regularly importing it doesn't work, because it doesn't have the 
```
export default FullCalendar
```
However, I am running into this problem now: 
```
TypeError: FullCalendar.Calendar is not a constructor
    at Proxy.mounted (fullcalendar.js:16:21)
    at vue.global.prod.js:3:2763
    at Lt (vue.global.prod.js:1:14684)
    at jt (vue.global.prod.js:1:14762)
    at t.__weh.t.__weh (vue.global.prod.js:3:2642)
    at nn (vue.global.prod.js:1:15988)
    at sn (vue.global.prod.js:1:16284)
(anonymous) @ vue.global.prod.js:1
Ut @ vue.global.prod.js:1
Lt @ vue.global.prod.js:1
jt @ vue.global.prod.js:1
t.__weh.t.__weh @ vue.global.prod.js:3
nn @ vue.global.prod.js:1
sn @ vue.global.prod.js:1
Promise.then (async)
Xt @ vue.global.prod.js:1
Qt @ vue.global.prod.js:1
(anonymous) @ vue.global.prod.js:3
Ne @ vue.global.prod.js:1
Ee @ vue.global.prod.js:1
Te @ vue.global.prod.js:1
set @ vue.global.prod.js:1
update @ documentation:579
await in update (async)
(anonymous) @ documentation:595
(anonymous) @ documentation:601
await in (anonymous) (async)
U.emit @ index.mjs:136
value @ socket.js:498
value @ socket.js:485
value @ socket.js:455
U.emit @ index.mjs:136
(anonymous) @ manager.js:204
Promise.then (async)
ut @ websocket-constructor.browser.js:5
value @ manager.js:203
U.emit @ index.mjs:136
value @ index.js:146
value @ manager.js:190
U.emit @ index.mjs:136
value @ socket.js:341
U.emit @ index.mjs:136
value @ transport.js:98
value @ transport.js:90
ws.onmessage @ websocket.js:68
```
Another thing is that the import isn't very pretty either..
Let me know what you think.

**Comment by falkoschindler** [comment]
Oh, I finally understand why

```py
ui.add_head_html('<script src="https://cdn.jsdelivr.net/npm/fullcalendar@6.1.9/index.global.min.js"></script>')
```

did work, but using `libraries=['lib/fullcalendar/index.global.min.js']` didn't: The latter assumes an ESM6 module syntax, but the JS file isn't.

This all seems closely related to https://github.com/zauberzeug/nicegui/discussions/1454 where I already struggled to include a third-party library. Somehow I'm loosing track of all these module syntaxes and how to import them properly. Right now I'm not sure if fullcalendar can be imported without modifications to the library or to NiceGUI.

I don't think Vue3 libraries will help, because they usually get compiled, which we can't do. Sure, if the package contains every bits and pieces we need, why not. But it looks like @fullcalendar/vue3 has dependencies, which we would need to resolve somehow.

Looks like I'll need some more time to think about it.

**Comment by frankvp11** [comment]
Alright, thanks for letting me know. I'll see if I can get the import working like how you did for the leaflet. 
Otherwise, I suppose I'll just have it locally 🙁

**Comment by frankvp11** [comment]
Awesome to hear this. Unfortunately, I am in the midst of exam season and don't/won't have time for ~2 weeks to actually work on this project. I plan to finish it when the break starts. 
Once my break starts, I will be sure to make an actual clean version of the PR, and tidy up some things (like how it appears on the page), and put some thought into how the user uses it.

**Comment by falkoschindler** [comment]
Good news, @frankvp11! Using new mechanics I developed for the new `ui.leaflet` element, I managed to integrate the FullCalendar dependency quite nicely: The Python instance calls `self.add_resource()` and the JavaScript component loads it using `await loadResource()`. And this also works for CSS files, in case one needs them.

After solving this technical issue, we should think about what the new `ui.calendar` element is missing. Should we provide something like `self.run_calendar_method()` to call arbitrary methods on the JavaScript instance? And the API for removing events seems a bit unconventional. It would be great to have something like `Event` objects that can be passed around. Oh and the click event feels a bit pointless, because it targets the <div>, not the `calendar` instance. It would be great if it would contain the clicked day or event.

What are your plans? Do you have more features in mind or should we merge early and improve later?

**Comment by frankvp11** [comment]
I was looking through the PR and it looks great! 
To answer your questions though, aside from what I planned on needing for my project, I didn't really think extensively about the element (:sweat_smile:). As for features, most of the features that are available with the fullcalendar JS side of things are already there in the options that the user passes. I like the idea of having a self.run_method function, as that would technically allow us to remove function that removes events (and adding for that matter). As for having Event objects, I'm not entirely sure of how we would do that (like whether we use the Python side or JS side, and how that would look like). As for the click event, I think that you got cut off.., but to answer the second part of that point, if you swap to using the timeGridWeek for initialView, and add an event, when you click on that event it will return a GenericEventArguments where the event that you clicked is found.
As for my personal plans, I'd like to perfect this (whatever that means), but in terms of the requirements that my initial project had it would be considered done (technically), but I'm happy to develop it further.

**Review by falkoschindler — APPROVED** [review]
@frankvp11 I came to the conclusion that it's still some work to do to turn the new fullcalendar into a proper NiceGUI element. Besides that, @retsyo brought a competitor [Toast UI Calendar](https://github.com/nhn/tui.calendar) to the table, which _might_ be a better alternative, see https://github.com/zauberzeug/nicegui/discussions/1878#discussioncomment-7936598.

Since I'm a bit undecided between FullCalendar and Toast UI Calendar, and finishing the element is taking more time and effort than anticipated, I decided to move your implementation into an example and merge the PR. This way it gets available to the community without adding another element that needs further development, documentation, support and maintenance. I hope you're ok with this decision.

Let's continue discussing pros and cons of various calendar libraries over at #1878. Maybe we'll agree on one or the other library and finally create an official calendar element for NiceGUI. 🙂

**Comment by knoxvilledatabase** [comment]
I only needed a simple month calendar for my project, in case this helps anyone. 

```python
from nicegui import ui
from datetime import datetime
import calendar

# Function to create the calendar table for a given month and year
def create_calendar(year, month):
    cal = calendar.Calendar(calendar.SUNDAY)
    month_days = cal.monthdayscalendar(year, month)

    # Prepare calendar data for ui.table
    calendar_rows = []
    for week in month_days:
        week_data = {f'day{i+1}': (day if day != 0 else '') for i, day in enumerate(week)}
        calendar_rows.append(week_data)

    # Define columns for each day of the week
    columns = [{'name': f'day{i+1}', 'label': day, 'field': f'day{i+1}'} for i, day in enumerate(['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'])]

    # Clear and create the calendar table
    calendar_div.clear()
    with calendar_div:
        with ui.row().classes("w-full flex justify-between items-center"):
            ui.button('<<', on_click=lambda: change_month(-1))
            ui.label(f'{calendar.month_name[month]} {year}').style('font-size: 20px; font-weight: bold;')
            ui.button('>>', on_click=lambda: change_month(1))
        ui.table(columns=columns, rows=calendar_rows)

# Get the current date
now = datetime.now()
current_year = now.year
current_month = now.month
calendar_div = ui.column()

# Function to change the month
def change_month(delta):
    global current_month, current_year
    current_month += delta
    if current_month > 12:
        current_month = 1
        current_year += 1
    elif current_month < 1:
        current_month = 12
        current_year -= 1
    create_calendar(current_year, current_month)

create_calendar(current_year, current_month)

ui.run()
```

**Pull request merged**
